import BusinessIcon from "@mui/icons-material/Business";
import ArticleIcon from "@mui/icons-material/Article";
import AssignmentIcon from "@mui/icons-material/Assignment";
import CalculateOutlinedIcon from '@mui/icons-material/CalculateOutlined';
import RateReviewOutlinedIcon from '@mui/icons-material/RateReviewOutlined';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
import FeaturedPlayListOutlinedIcon from '@mui/icons-material/FeaturedPlayListOutlined';
import TextSnippetOutlinedIcon from '@mui/icons-material/TextSnippetOutlined';
import EqualizerOutlinedIcon from '@mui/icons-material/EqualizerOutlined';
import DashboardOutlinedIcon from '@mui/icons-material/DashboardOutlined';
import ChromeReaderModeOutlinedIcon from '@mui/icons-material/ChromeReaderModeOutlined';
import WebAssetOutlinedIcon from '@mui/icons-material/WebAssetOutlined';
import BookOutlinedIcon from '@mui/icons-material/BookOutlined';
import BorderAllOutlinedIcon from '@mui/icons-material/BorderAllOutlined';
import TimelineRoundedIcon from '@mui/icons-material/TimelineRounded';
import WaterDropRoundedIcon from '@mui/icons-material/WaterDropRounded';
import PeopleOutlineOutlinedIcon from '@mui/icons-material/PeopleOutlineOutlined';
import DonutSmallOutlinedIcon from '@mui/icons-material/DonutSmallOutlined';
import OpacityRoundedIcon from '@mui/icons-material/OpacityRounded';
import RepeatOutlinedIcon from '@mui/icons-material/RepeatOutlined';
import BallotOutlinedIcon from '@mui/icons-material/BallotOutlined';
import TrendingUpOutlinedIcon from '@mui/icons-material/TrendingUpOutlined';
import InsertDriveFileOutlinedIcon from '@mui/icons-material/InsertDriveFileOutlined';
import NoteAddOutlinedIcon from '@mui/icons-material/NoteAddOutlined';
import PermContactCalendarOutlinedIcon from '@mui/icons-material/PermContactCalendarOutlined';

export const originalMenu = [
    {
        id: 1,
        url: "dam",
        name: "DAM",
        icon: <PeopleOutlineOutlinedIcon />,
        iconSize: <PeopleOutlineOutlinedIcon style={{ fontSize: "72px" }} />,
        active: true,
        toggle: false,
        shortcut: ["d"],
        keywords: "d",
        section: "Dam",
        subtitle: "DAM",
        menus_config_id: 9,
        menu: [
            {
                id: 11,
                url: "dam/userManagement",
                name: "User Management",
                icon: <BusinessIcon />,
                iconSize: <BusinessIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["dum"],
                keywords: "dum",
                section: "Dam",
                subtitle: "DAM > User Management",
                menus_config_id: 10,
                menu: [
                    {
                        id: 111,
                        url: "dam/userManagement/group",
                        name: "Group",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umg"],
                        keywords: "umg",
                        section: "Dam",
                        subtitle: "Dam > User Management > Group",
                        menus_config_id: 11,
                        menu: [
                            {
                                id: 1111,
                                url: "dam/userManagement/group/tso",
                                name: "TSO Group",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgtso"],
                                keywords: "umgtso",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > TSO",
                                menus_config_id: 13,
                                menu: [],
                            },
                            {
                                id: 1112,
                                url: "dam/userManagement/group/shippers",
                                name: "Shippers Group",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgshp"],
                                keywords: "umgshp",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > Shippers",
                                menus_config_id: 12,
                                menu: [],
                            },
                            {
                                id: 1113,
                                url: "dam/userManagement/group/other",
                                name: "Other Group",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgotr"],
                                keywords: "umgotr",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > Other",
                                menus_config_id: 14,
                                menu: [],
                            },
                        ],
                    },
                    {
                        id: 112,
                        url: "dam/userManagement/divisions",
                        name: "Divisions",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umd"],
                        keywords: "umd",
                        section: "Dam",
                        subtitle: "Dam > User Management > Divisions",
                        menus_config_id: 15,
                        menu: [],
                    },
                    {
                        id: 113,
                        url: "dam/userManagement/users",
                        name: "Users",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umuser"],
                        keywords: "umuser",
                        section: "Dam",
                        subtitle: "Dam > User Management > Users",
                        menus_config_id: 16,
                        menu: [],
                    },
                    {
                        id: 114,
                        url: "dam/userManagement/roles",
                        name: "Roles",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umrole"],
                        keywords: "umrole",
                        section: "Dam",
                        subtitle: "Dam > User Management > Roles",
                        menus_config_id: 17,
                        menu: [],
                    },
                    {
                        id: 115,
                        url: "dam/userManagement/systemLogin",
                        name: "System Login",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umsyslgn"],
                        keywords: "umsyslgn",
                        section: "Dam",
                        subtitle: "Dam > User Management > System Login",
                        menus_config_id: 18,
                        menu: [],
                    },
                ],
            },
            {
                id: 12,
                url: "dam/Assets",
                name: "Assets",
                icon: <AssignmentIcon />,
                iconSize: <AssignmentIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["da"],
                keywords: "da",
                section: "Dam",
                subtitle: "DAM > Assets",
                menus_config_id: 19,
                menu: [
                    {
                        id: 1201,
                        url: "dam/Assets/zone",
                        name: "Zone",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["daz"],
                        keywords: "daz",
                        section: "Dam",
                        subtitle: "DAM > Assets > Zone",
                        menus_config_id: 20,
                        menu: [],
                    },
                    {
                        id: 1202,
                        url: "dam/Assets/area",
                        name: "Area",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["daa"],
                        keywords: "daa",
                        section: "Dam",
                        subtitle: "DAM > Assets > Area",
                        menus_config_id: 21,
                        menu: [],
                    },
                    {
                        id: 1203,
                        url: "dam/Assets/configMasterPath",
                        name: "Config Master Path",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dacfgpath"],
                        keywords: "dacfgpath",
                        section: "Dam",
                        subtitle: "DAM > Assets > Config Master Path",
                        menus_config_id: 22,
                        menu: [],
                    },
                    {
                        id: 1204,
                        url: "dam/Assets/contractPoint",
                        name: "Contract Point",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dacp"],
                        keywords: "dacp",
                        section: "Dam",
                        subtitle: "DAM > Assets > Contract Point",
                        menus_config_id: 23,
                        menu: [],
                    },
                    {
                        id: 1205,
                        url: "dam/Assets/nominationPoint",
                        name: "Nomination Point",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["danp"],
                        keywords: "danp",
                        section: "Dam",
                        subtitle: "DAM > Assets > Nomination Point",
                        menus_config_id: 24,
                        menu: [],
                    },
                    {
                        id: 1206,
                        url: "dam/Assets/nonTpaPoint",
                        name: "Non TPA Point",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["danontpa"],
                        keywords: "danontpa",
                        section: "Dam",
                        subtitle: "DAM > Assets > Non TPA Point",
                        menus_config_id: 25,
                        menu: [],
                    },
                    {
                        id: 1207,
                        url: "dam/Assets/meteredPoint",
                        name: "Metered Point",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["damp"],
                        keywords: "damp",
                        section: "Dam",
                        subtitle: "DAM > Assets > Metered Point",
                        menus_config_id: 26,
                        menu: [],
                    },
                    // {
                    //   id: 127,
                    //   url: "dam/Assets/qualityPoint",
                    //   name: "Quality Point",
                    //   icon: null,
                    //   active: true,
                    //   toggle: false,
                    //   shortcut: ["daqp"],
                    //   keywords: "daqp",
                    //   section: "Dam",
                    //   subtitle: "Dam > Assets > Quality Point",
                    //   menu: [],
                    // },
                    {
                        id: 1208,
                        url: "dam/Assets/conceptPoint",
                        name: "Concept Point",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["daccp"],
                        keywords: "daccp",
                        section: "Dam",
                        subtitle: "DAM > Assets > Concept Point",
                        menus_config_id: 27,
                        menu: [],
                    },
                    // {
                    //   id: 129,
                    //   url: "dam/Assets/contractNomPointRelation",
                    //   name: "Contract Nom. Point Relation",
                    //   icon: null,
                    //   active: true,
                    //   toggle: false,
                    //   shortcut: ["dacnpr"],
                    //   keywords: "dacnpr",
                    //   section: "Dam",
                    //   subtitle: "Dam > Assets > Contract Nom. Point Relation",
                    //   menu: [],
                    // },
                    {
                        id: 1210,
                        url: "dam/Assets/customerType",
                        name: "Customer Type",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dacusttype"],
                        keywords: "dacusttype",
                        section: "Dam",
                        subtitle: "DAM > Assets > Customer Type",
                        menu: [],
                    },
                ],
            },
            {
                id: 13,
                url: "dam/parameters",
                name: "Parameters",
                icon: <ArticleIcon />,
                iconSize: <ArticleIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["dp"],
                keywords: "dp",
                section: "Dam",
                subtitle: "DAM > Parameters",
                menus_config_id: 30,
                menu: [
                    {
                        id: 1301,
                        url: "dam/parameters/nomiDeadline",
                        name: "Nomination Deadline",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpde"],
                        keywords: "dpde",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Nomination Deadline",
                        menus_config_id: 31,
                        menu: [],
                    },
                    {
                        id: 1302,
                        url: "dam/parameters/planDeadline",
                        name: "Planning Deadline",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dppd"],
                        keywords: "dppd",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Planning Deadline",
                        menus_config_id: 32,
                        menu: [],
                    },
                    {
                        id: 1303,
                        url: "dam/parameters/announcement",
                        name: "Announcement",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpan"],
                        keywords: "dpan",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Announcement",
                        menus_config_id: 38,
                        menu: [],
                    },
                    {
                        id: 1304,
                        url: "dam/parameters/systemParameter",
                        name: "System Parameter",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpsp"],
                        keywords: "dpsp",
                        section: "Dam",
                        subtitle: "DAM > Parameters > System Parameter",
                        menus_config_id: 34,
                        menu: [],
                    },
                    {
                        id: 1305,
                        url: "dam/parameters/emailNotiManage",
                        name: "Email Notification Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpenmgn"],
                        keywords: "dpenmgn",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Email Notification Management",
                        menus_config_id: 35,
                        menu: [],
                    },
                    {
                        id: 1306,
                        url: "dam/parameters/userGuide",
                        name: "User Guide",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpug"],
                        keywords: "dpug",
                        section: "Dam",
                        subtitle: "DAM > Parameters > User Guide",
                        menus_config_id: 36,
                        menu: [],
                    },
                    {
                        id: 1307,
                        url: "dam/parameters/auditLog",
                        name: "Audit Log",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpal"],
                        keywords: "dpal",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Audit Log",
                        menus_config_id: 41,
                        menu: [],
                    },
                    {
                        id: 1308,
                        url: "dam/parameters/capacityPublicRemark",
                        name: "Capacity Publication Remark",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpcappubrem"],
                        keywords: "dpcappubrem",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Capacity Publication Remark",
                        menus_config_id: 40,
                        menu: [],
                    },
                    {
                        id: 1309,
                        url: "dam/parameters/setupBackground",
                        name: "Setup Background",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpsetbg"],
                        keywords: "dpsetbg",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Setup Background",
                        menus_config_id: 43,
                        menu: [],
                    },
                    {
                        id: 1310,
                        url: "dam/parameters/termAndCondition",
                        name: `Terms & Conditions`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dptandc"],
                        keywords: "dptandc",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Terms & Conditions",
                        menus_config_id: 39,
                        menu: [],
                    },
                    {
                        id: 1311,
                        url: "dam/parameters/meteringCheckingCondition",
                        name: `Metering Checking Condition`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpmechkcon"],
                        keywords: "dpmechkcon",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Metering Checking Condition",
                        menu: [],
                    },
                    {
                        id: 1312,
                        url: "dam/parameters/bookingTemplate",
                        name: `Booking Template`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpbktp"],
                        keywords: "dpbktp",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Booking Template",
                        menus_config_id: 42,
                        menu: [],
                    },
                    {
                        id: 1313,
                        url: "dam/parameters/configModeZoneBaseInven",
                        name: `Config Mode/Zone Base Inventory`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpcgmdznba"],
                        keywords: "dpcgmdznba",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Config Mode/Zone Base Inventory",
                        menu: [],
                    },
                    {
                        id: 1314,
                        url: "dam/parameters/modeZoneBaseInven",
                        name: `Mode/Zone Base Inventory`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpmdznba"],
                        keywords: "dpmdznba",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Mode/Zone Base Inventory",
                        menus_config_id: 37,
                        menu: [],
                    },
                    {
                        id: 1315,
                        url: "dam/parameters/emailGroupForEvent",
                        name: `Email Group For Event`,
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpegfe"],
                        keywords: "dpegfe",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Email Group For Event",
                        menu: [],
                    },
                ],
            },
        ],
    },
    {
        id: 101,
        url: "booking",
        name: "Capacity Management",
        icon: <BookOutlinedIcon />,
        iconSize: <BookOutlinedIcon style={{ fontSize: "57px" }} />,
        active: true,
        toggle: false,
        shortcut: ["b"],
        keywords: "b",
        section: "Capacity Management",
        subtitle: "Capacity Management",
        menus_config_id: 49,
        menu: [
            {
                id: 2001,
                url: "booking/bulletinBoard",
                name: "Bulletin Board",
                icon: <BorderAllOutlinedIcon />,
                iconSize: <BorderAllOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkblb"],
                keywords: "bkblb",
                section: "Capacity Management",
                subtitle: "Capacity Management > Bulletin Board",
                menus_config_id: 52,
                menu: []
            },
            {
                id: 2003,
                url: "booking/capacity",
                name: "Capacity",
                icon: <WaterDropRoundedIcon />,
                iconSize: <WaterDropRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkcap"],
                keywords: "bkcap",
                section: "Capacity Management",
                subtitle: "Capacity Management > Capacity",
                menus_config_id: 49,
                menu: [
                    {
                        id: 200302,
                        url: "booking/capacity/CapPublication",
                        name: "Capacity Publication",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcappub"],
                        keywords: "bkcappub",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Capacity > Capacity Publication",
                        menus_config_id: 54,
                        menu: [],
                    },
                    {
                        id: 200303,
                        url: "booking/capacity/CapacityChart",
                        name: "Capacity Chart",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcapchart"],
                        keywords: "bkcapchart",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Capacity > Capacity Chart",
                        menus_config_id: 55,
                        menu: [],
                    },
                    {
                        id: 200301,
                        url: "booking/capacity/CapReqMgn",
                        name: "Capacity Contract Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcapreqmgn"],
                        keywords: "bkcapreqmgn",
                        section: "Capacity Management",
                        // subtitle: "Booking > Capacity > Capacity Request Management",
                        subtitle: "Capacity Management > Capacity > Capacity Contract Management",
                        menus_config_id: 50,
                        menu: [],
                    },
                    {
                        id: 200304,
                        url: "booking/capacity/CapContractList",
                        name: "Capacity Contract List",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcontlist"],
                        keywords: "bkcontlist",
                        section: "Capacity Management",
                        // subtitle: "Booking > Capacity > Capacity Request Management",
                        subtitle: "Capacity Management > Capacity > Capacity Contract List",
                        menus_config_id: 53,
                        menu: [],
                    },

                ]
            },
            {
                id: 2004,
                url: "booking/release",
                name: "Release",
                icon: <OpacityRoundedIcon />,
                iconSize: <OpacityRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkrel"],
                keywords: "bkrel",
                section: "Capacity Management",
                subtitle: "Capacity Management > Release",
                menus_config_id: 49,
                menu: [
                    {
                        id: 200401,
                        url: "booking/release/ReleaseCapSubmission",
                        name: "Release Capacity Submission",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelcapsub"],
                        keywords: "bkrelcapsub",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release Capacity Submission",
                        menus_config_id: 56,
                        menu: [],
                    },
                    {
                        id: 200402,
                        url: "booking/release/ReleaseCapManagement",
                        name: "Release Capacity Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelcapmgn"],
                        keywords: "bkrelcapmgn",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release Capacity Management",
                        menus_config_id: 60,
                        menu: [],
                    },
                    {
                        id: 200403,
                        url: "booking/release/ReleaseSumManagement",
                        name: "Release/UIOLI Summary Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelsummgn"],
                        keywords: "bkrelsummgn",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release/UIOLI Summary Management",
                        menus_config_id: 58,
                        menu: [],
                    },
                ]
            },
            {
                id: 2005,
                url: "booking/useItOrLoseIt",
                name: "Use It or Lose It",
                icon: <RepeatOutlinedIcon />,
                iconSize: <RepeatOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkuioli"],
                keywords: "bkuioli",
                section: "Capacity Management",
                subtitle: "Capacity Management > Use It or Lose It",
                menus_config_id: 57,
                menu: []
            },
            {
                id: 2006,
                url: "booking/reserveBalGasContracts",
                name: "Reserve Balancing Gas Contracts",
                icon: <BallotOutlinedIcon />,
                iconSize: <BallotOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkresbalgascon"],
                keywords: "bkresbalgascon",
                section: "Capacity Management",
                subtitle: "Capacity Management > Reserve Balancing Gas Contracts ",
                menus_config_id: 59,
                menu: []
            },
            {
                id: 2002,
                url: "booking/pathManagement",
                name: "Path Management",
                icon: <TimelineRoundedIcon />,
                iconSize: <TimelineRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkpmgn"],
                keywords: "bkpmgn",
                section: "Capacity Management",
                subtitle: "Capacity Management > Path Management",
                menus_config_id: 51,
                menu: []
            },
        ],
    },
    {
        id: 201,
        url: "allocation",
        name: "Allocation",
        icon: <CalculateOutlinedIcon />,
        iconSize: <CalculateOutlinedIcon style={{ fontSize: "65px" }} />,
        active: true,
        toggle: false,
        shortcut: ["al"],
        keywords: "al",
        section: "Allocation",
        subtitle: "Allocation",
        menus_config_id: 80,
        menu: [
            {
                id: 2001,
                url: "allocation/alloReview",
                name: "Allocation Review",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alre"],
                keywords: "alre",
                section: "Allocation",
                subtitle: "Allocation > Allocation Review",
                menus_config_id: 81,
                menu: []
            },
            {
                id: 2002,
                url: "allocation/alloManage",
                name: "Allocation Management",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alma"],
                keywords: "alma",
                section: "Allocation",
                subtitle: "Allocation > Allocation Management",
                menus_config_id: 82,
                menu: []
            },
            {
                id: 2003,
                url: "allocation/alloQuery",
                name: "Allocation Query",
                icon: <FeaturedPlayListOutlinedIcon />,
                iconSize: <FeaturedPlayListOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alque"],
                keywords: "alque",
                section: "Allocation",
                subtitle: "Allocation > Allocation Query",
                menus_config_id: 83,
                menu: []
            },
            {
                id: 2004,
                url: "allocation/alloReport",
                name: "Allocation Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alrep"],
                keywords: "alrep",
                section: "Allocation",
                subtitle: "Allocation > Allocation Report",
                menus_config_id: 84,
                menu: []
            },
            {
                id: 2005,
                url: "allocation/alloMonthReport",
                name: "Allocation Monthly Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["almorep"],
                keywords: "almorep",
                section: "Allocation",
                subtitle: "Allocation > Allocation Monthly Report",
                menus_config_id: 86,
                menu: []
            },
            {
                id: 2006,
                url: "allocation/alloCurtailReport",
                name: "Curtailments Allocation Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alcurrep"],
                keywords: "alcurrep",
                section: "Allocation",
                subtitle: "Allocation > Curtailments Allocation Report",
                menus_config_id: 85,
                menu: []
            },
        ],
    },
    {
        id: 301,
        url: "balancing",
        name: "Balancing",
        icon: <EqualizerOutlinedIcon />,
        iconSize: <EqualizerOutlinedIcon style={{ fontSize: "68px" }} />,
        active: true,
        toggle: false,
        shortcut: ["al"],
        keywords: "al",
        section: "Balancing",
        subtitle: "Balancing",
        menus_config_id: 87,
        menu: [
            {
                id: 3001,
                url: "balancing/balIntraDash",
                name: "Intraday Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balindash"],
                keywords: "balindash",
                section: "Balancing",
                subtitle: "Balancing > Intraday Dashboard",
                menus_config_id: 90,
                menu: []
            },
            {
                id: 3002,
                url: "balancing/balOperateFlowOrder",
                name: "Operation Flow and Instructed Flow Order",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["baloperateflow"],
                keywords: "baloperateflow",
                section: "Balancing",
                subtitle: "Balancing > Operation Flow and Instructed Flow Order",
                menus_config_id: 89,
                menu: []
            },
            {
                id: 3003,
                url: "balancing/balReport",
                name: "Balance Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balreport"],
                keywords: "balreport",
                section: "Balancing",
                subtitle: "Balancing > Balance Report",
                menus_config_id: 94,
                menu: []
            },
            {
                id: 3004,
                url: "balancing/balMgn",
                name: "Balance Management",
                icon: <ChromeReaderModeOutlinedIcon />,
                iconSize: <ChromeReaderModeOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balmgn"],
                keywords: "balmgn",
                section: "Balancing",
                subtitle: "Balancing > Balance Management",
                menus_config_id: 91,
                menu: []
            },
            {
                id: 3005,
                url: "balancing/balIntraBalReport",
                name: "Intraday Balancing Report",
                icon: <ChromeReaderModeOutlinedIcon />,
                iconSize: <ChromeReaderModeOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbalrep"],
                keywords: "balinbalrep",
                section: "Balancing",
                subtitle: "Balancing > Intraday Balancing Report",
                menus_config_id: 93,
                menu: []
            },
            {
                id: 3006,
                url: "balancing/balIntraBalReportShp",
                name: "Intraday Balancing Report For Shipper ",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbalrepshp"],
                keywords: "balinbalrepshp",
                section: "Balancing",
                subtitle: "Balancing > Intraday Balancing Report For Shipper ",
                menus_config_id: 92,
                menu: []
            },
            {
                id: 3007,
                url: "balancing/balIntraAccImInven",
                name: "Intraday Acc. Imbalance inventory",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinacciminven"],
                keywords: "balinacciminven",
                section: "Balancing",
                subtitle: "Balancing > Intraday Acc. Imbalance inventory",
                menus_config_id: 95,
                menu: []
            },
            {
                id: 3008,
                url: "balancing/balIntraBaseInven",
                name: "Intraday Base Inventory",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbaseinven"],
                keywords: "balinbaseinven",
                section: "Balancing",
                subtitle: "Balancing > Intraday Base Inventory",
                menus_config_id: 96,
                menu: []
            },
            {
                id: 3009,
                url: "balancing/balVenComOthGas",
                name: "Vent/Commissioning/Other Gas ",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balventcomothgas"],
                keywords: "balventcomothgas",
                section: "Balancing",
                subtitle: "Balancing > Vent/Commissioning/Other Gas ",
                menus_config_id: 88,
                menu: []
            },
            {
                id: 3010,
                url: "balancing/balVenComOthGas",
                name: "Vent/Commissioning/Other Gas",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balventcomothgas"],
                keywords: "balventcomothgas",
                section: "Balancing",
                subtitle: "Balancing > Vent/Commissioning/Other Gas",
                menus_config_id: 88,
                menu: []
            },
            {
                id: 3011,
                url: "balancing/balAdjust",
                name: "Adjustment",
                icon: <WebAssetOutlinedIcon />,
                iconSize: <WebAssetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["baladjust"],
                keywords: "baladjust",
                section: "Balancing",
                subtitle: "Balancing > Adjustment",
                menus_config_id: 98,
                menu: [
                    {
                        id: 30111,
                        url: "balancing/balAdjust/inTraAccImbalInvenAdjust",
                        name: "Intraday Acc. Imbalance Inventory Adjust",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjintraaccim"],
                        keywords: "baladjintraaccim",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Intraday Acc. Imbalance Inventory Adjust",
                        menus_config_id: 99,
                        menu: [],
                    },
                    {
                        id: 30112,
                        url: "balancing/balAdjust/adjustDailyImbal",
                        name: "Adjustment Daily Imbalance",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjdailimbal"],
                        keywords: "baladjdailimbal",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Adjustment Daily Imbalance",
                        menus_config_id: 100,
                        menu: [],
                    },
                    {
                        id: 30113,
                        url: "balancing/balAdjust/adjustImbalAlloc",
                        name: "Adjust Imbalance Allocation",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjimbalalloc"],
                        keywords: "baladjimbalalloc",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Adjust Imbalance Allocation",
                        menus_config_id: 101,
                        menu: [],
                    },
                ],
            },
            {
                id: 3012,
                url: "balancing/balSystemAcc",
                name: "System Acc. IMB.",
                icon: <EqualizerOutlinedIcon />,
                iconSize: <EqualizerOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balsysacc"],
                keywords: "balsysacc",
                section: "Balancing",
                subtitle: "Balancing > System Acc. IMB.",
                menus_config_id: 97,
                menu: []
            },
        ]
    },
    {
        id: 401,
        url: "pmis.pipeline.pttplc.com/smartTSO/login.php",
        name: "PMIS Graphics",
        icon: <DonutSmallOutlinedIcon />,
        iconSize: <DonutSmallOutlinedIcon style={{ fontSize: "68px" }} />,
        active: true,
        toggle: false,
        // shortcut: ["al"],
        // keywords: "al",
        section: "PMIS Graphics",
        subtitle: "PMIS Graphics",
        menu: []
    },
    {
        id: 501,
        url: "planning",
        name: "Planning",
        icon: <TrendingUpOutlinedIcon />,
        iconSize: <TrendingUpOutlinedIcon style={{ fontSize: "68px" }} />,
        active: true,
        toggle: false,
        // shortcut: ["al"],
        // keywords: "al",
        section: "Planning",
        subtitle: "Planning",
        menus_config_id: 44,
        menu: [
            {
                id: 5001,
                url: "planning/planningDashboard",
                name: "Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plndash"],
                keywords: "plndash",
                section: "Planning",
                subtitle: "Planning > Planning Dashboard",
                menus_config_id: 45,
                menu: []
            },
            {
                id: 5005,
                url: "planning/planningFileSubmissionTemplate",
                name: "Planning File Submission Template",
                icon: <PermContactCalendarOutlinedIcon />,
                iconSize: <PermContactCalendarOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnfilesubtemp"],
                keywords: "plnfilesubtemp",
                section: "Planning",
                subtitle: "Planning > Planning File Submission Template",
                menus_config_id: 1001,
                menu: []
            },
            {
                id: 5003,
                url: "planning/planningSubmissionFiles",
                name: "Planning Submission File",
                icon: <BorderAllOutlinedIcon />,
                iconSize: <BorderAllOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnsubfile"],
                keywords: "plnsubfile",
                section: "Planning",
                subtitle: "Planning > Planning Submission File",
                menus_config_id: 47,
                menu: []
            },
            {
                id: 5002,
                url: "planning/planningQueryShipperFiles",
                name: "Query Shippers' Planning Files",
                icon: <InsertDriveFileOutlinedIcon />,
                iconSize: <InsertDriveFileOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnqueshpfile"],
                keywords: "plnqueshpfile",
                section: "Planning",
                subtitle: "Planning > Query Shippers' Planning Files",
                menus_config_id: 46,
                menu: []
            },
            {
                id: 5004,
                url: "planning/planningNewPoint",
                name: "New Point",
                icon: <NoteAddOutlinedIcon />,
                iconSize: <NoteAddOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnnewpoint"],
                keywords: "plnnewpoint",
                section: "Planning",
                subtitle: "Planning > New Point",
                menus_config_id: 48,
                menu: []
            },
        ]
    }
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
]