import BusinessIcon from "@mui/icons-material/Business";
import ArticleIcon from "@mui/icons-material/Article";
import AssignmentIcon from "@mui/icons-material/Assignment";
import CalculateOutlinedIcon from '@mui/icons-material/CalculateOutlined';
import RateReviewOutlinedIcon from '@mui/icons-material/RateReviewOutlined';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
import FeaturedPlayListOutlinedIcon from '@mui/icons-material/FeaturedPlayListOutlined';
import TextSnippetOutlinedIcon from '@mui/icons-material/TextSnippetOutlined';
import EqualizerOutlinedIcon from '@mui/icons-material/EqualizerOutlined';
import DashboardOutlinedIcon from '@mui/icons-material/DashboardOutlined';
import ChromeReaderModeOutlinedIcon from '@mui/icons-material/ChromeReaderModeOutlined';
import WebAssetOutlinedIcon from '@mui/icons-material/WebAssetOutlined';
import BookOutlinedIcon from '@mui/icons-material/BookOutlined';
import BorderAllOutlinedIcon from '@mui/icons-material/BorderAllOutlined';
import TimelineRoundedIcon from '@mui/icons-material/TimelineRounded';
import WaterDropRoundedIcon from '@mui/icons-material/WaterDropRounded';
import PeopleOutlineOutlinedIcon from '@mui/icons-material/PeopleOutlineOutlined';
import DonutSmallOutlinedIcon from '@mui/icons-material/DonutSmallOutlined';
import OpacityRoundedIcon from '@mui/icons-material/OpacityRounded';
import RepeatOutlinedIcon from '@mui/icons-material/RepeatOutlined';
import BallotOutlinedIcon from '@mui/icons-material/BallotOutlined';
import TrendingUpOutlinedIcon from '@mui/icons-material/TrendingUpOutlined';
import InsertDriveFileOutlinedIcon from '@mui/icons-material/InsertDriveFileOutlined';
import NoteAddOutlinedIcon from '@mui/icons-material/NoteAddOutlined';
import PermContactCalendarOutlinedIcon from '@mui/icons-material/PermContactCalendarOutlined';
import ImageAspectRatioOutlinedIcon from '@mui/icons-material/ImageAspectRatioOutlined';
import UploadOutlinedIcon from '@mui/icons-material/UploadOutlined';
import VerifiedOutlinedIcon from '@mui/icons-material/VerifiedOutlined';
import ReportProblemOutlinedIcon from '@mui/icons-material/ReportProblemOutlined';
import TableViewIcon from '@mui/icons-material/TableView';
import CalendarTodayOutlinedIcon from '@mui/icons-material/CalendarTodayOutlined';
import WaterDropSharpIcon from '@mui/icons-material/WaterDropSharp';
import WarningAmberOutlinedIcon from '@mui/icons-material/WarningAmberOutlined';
import SwapHorizontalCircleOutlinedIcon from '@mui/icons-material/SwapHorizontalCircleOutlined';
import PaymentsOutlinedIcon from '@mui/icons-material/PaymentsOutlined';
import CreditCardOutlinedIcon from '@mui/icons-material/CreditCardOutlined';
import ViewAgendaOutlinedIcon from '@mui/icons-material/ViewAgendaOutlined';
import PieChartOutlineOutlinedIcon from '@mui/icons-material/PieChartOutlineOutlined';

export const originalMenu = [
    {
        id: 1,
        url: "dam",
        name: "DAM",
        icon: <PeopleOutlineOutlinedIcon />,
        iconSize: <PeopleOutlineOutlinedIcon className="!text-[40px] md:!text-[55px] lg:!text-[72px]" />,
        active: true,
        toggle: false,
        shortcut: ["d"],
        keywords: "d",
        section: "Dam",
        subtitle: "DAM",
        menus_config_id: 9,
        menu: [
            {
                id: 11,
                url: "dam/userManagement",
                name: "Administration",
                icon: <BusinessIcon />,
                iconSize: <BusinessIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["dum"],
                keywords: "dum",
                section: "Dam",
                subtitle: "DAM > User Management",
                menus_config_id: 10,
                menu: [
                    {
                        id: 111,
                        url: "dam/userManagement/group",
                        name: "Group",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umg"],
                        keywords: "umg",
                        section: "Dam",
                        subtitle: "Dam > User Management > Group",
                        menus_config_id: 11,
                        menu: [
                            {
                                id: 1111,
                                url: "dam/userManagement/group/tso",
                                name: "TSO",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgtso"],
                                keywords: "umgtso",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > TSO",
                                menus_config_id: 13,
                                menu: [],
                            },
                            {
                                id: 1112,
                                url: "dam/userManagement/group/shippers",
                                name: "Shippers",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgshp"],
                                keywords: "umgshp",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > Shippers",
                                menus_config_id: 12,
                                menu: [],
                            },
                            {
                                id: 1113,
                                url: "dam/userManagement/group/other",
                                name: "Other",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["umgotr"],
                                keywords: "umgotr",
                                section: "Dam",
                                subtitle: "Dam > User Management > Group > Other",
                                menus_config_id: 14,
                                menu: [],
                            },
                        ],
                    },
                    {
                        id: 113,
                        url: "dam/userManagement/users",
                        name: "Users",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umuser"],
                        keywords: "umuser",
                        section: "Dam",
                        subtitle: "Dam > User Management > Users",
                        menus_config_id: 16,
                        menu: [],
                    },
                    {
                        id: 114,
                        url: "dam/userManagement/roles",
                        name: "Roles",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umrole"],
                        keywords: "umrole",
                        section: "Dam",
                        subtitle: "Dam > User Management > Roles",
                        menus_config_id: 17,
                        menu: [],
                    },
                    {
                        id: 115,
                        url: "dam/userManagement/systemLogin",
                        name: "Login Management Tool",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umsyslgn"],
                        keywords: "umsyslgn",
                        section: "Dam",
                        subtitle: "Dam > User Management > System Login",
                        menus_config_id: 18,
                        menu: [],
                    },
                    {
                        id: 112,
                        url: "dam/userManagement/divisions",
                        name: "Division Master",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["umd"],
                        keywords: "umd",
                        section: "Dam",
                        subtitle: "Dam > User Management > Divisions",
                        menus_config_id: 15,
                        menu: [],
                    },
                    {
                        id: 1307,
                        url: "dam/userManagement/auditLog",
                        name: "Audit Log",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpal"],
                        keywords: "dpal",
                        section: "Dam",
                        subtitle: "Dam > User Management > Audit Log",
                        menus_config_id: 41,
                        menu: [],
                    },
                ],
            },
            {
                id: 13,
                url: "dam/parameters",
                name: "Parameters",
                icon: <ArticleIcon />,
                iconSize: <ArticleIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["dp"],
                keywords: "dp",
                section: "Dam",
                subtitle: "DAM > Parameters",
                menus_config_id: 30,
                menu: [
                    {
                        id: 1316,
                        url: "dam/parameters/masterData",
                        name: "Master Data",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpmastdata"],
                        keywords: "dpmastdata",
                        section: "Dam",
                        subtitle: "DAM > Parameters > Master Data",
                        menus_config_id: 1003,
                        menu: [
                            {
                                id: 1201,
                                url: "dam/parameters/masterData/zone",
                                name: "Zone",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["daz"],
                                keywords: "daz",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Zone",
                                menus_config_id: 20,
                                menu: [],
                            },
                            {
                                id: 1202,
                                url: "dam/parameters/masterData/area",
                                name: "Area",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["daa"],
                                keywords: "daa",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Area",
                                menus_config_id: 21,
                                menu: [],
                            },
                            {
                                id: 1210,
                                url: "dam/parameters/masterData/customerType",
                                name: "Customer Type",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dacusttype"],
                                keywords: "dacusttype",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Customer Type",
                                menus_config_id: 1002,
                                menu: [],
                            },
                            {
                                id: 1204,
                                url: "dam/parameters/masterData/contractPoint",
                                name: "Contract Point",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dacp"],
                                keywords: "dacp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Contract Point",
                                menus_config_id: 23,
                                menu: [],
                            },
                            {
                                id: 1205,
                                url: "dam/parameters/masterData/nominationPoint",
                                name: "Nomination Point",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["danp"],
                                keywords: "danp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Nomination Point",
                                menus_config_id: 24,
                                menu: [],
                            },
                            {
                                id: 1207,
                                url: "dam/parameters/masterData/meteredPoint",
                                name: "Metered Point",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["damp"],
                                keywords: "damp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Metered Point",
                                menus_config_id: 26,
                                menu: [],
                            },
                            {
                                id: 1208,
                                url: "dam/parameters/masterData/conceptPoint",
                                name: "Concept Point",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["daccp"],
                                keywords: "daccp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Concept Point",
                                menus_config_id: 27,
                                menu: [],
                            },
                            {
                                id: 1206,
                                url: "dam/parameters/masterData/nonTpaPoint",
                                name: "Non TPA Point",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["danontpa"],
                                keywords: "danontpa",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Non TPA Point",
                                menus_config_id: 25,
                                menu: [],
                            },
                            {
                                id: 1203,
                                url: "dam/parameters/masterData/configMasterPath",
                                name: "Config Master Path",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dacfgpath"],
                                keywords: "dacfgpath",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Config Master Path",
                                menus_config_id: 22,
                                menu: [],
                            },
                            // {
                            //     id: 1203,
                            //     url: "dam/Assets/configMasterPath",
                            //     name: "Config Master Path",
                            //     icon: null,
                            //     active: true,
                            //     toggle: false,
                            //     shortcut: ["dacfgpath"],
                            //     keywords: "dacfgpath",
                            //     section: "Dam",
                            //     subtitle: "DAM > Assets > Config Master Path",
                            //     menus_config_id: 22,
                            //     menu: [],
                            // },
                            {
                                id: 1314,
                                url: "dam/parameters/masterData/modeZoneBaseInventory",
                                // name: `Mode/Zone Base Inventory`,
                                name: `Mode/Zone Baseline Inventory`, // ชื่อเมนูผิด ปรับเป็นชื่อ Mode/Zone Baseline Inventory https://app.clickup.com/t/86eu786aw
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpmdznba"],
                                keywords: "dpmdznba",
                                section: "Dam",
                                subtitle: "DAM > Parameters > Master Data > Mode/Zone Baseline Inventory",
                                menus_config_id: 37,
                                menu: [],
                            },
                        ],
                    },
                    // {
                    //     id: 1317,
                    //     url: "dam/parameters/systemParameters",
                    //     name: "System Parameter",
                    //     icon: null,
                    //     active: true,
                    //     toggle: false,
                    //     shortcut: ["dpsyspa"],
                    //     keywords: "dpsyspa",
                    //     section: "Parameters",
                    //     subtitle: "DAM > Parameters > System Parameter",
                    //     menus_config_id: 1005,
                    //     menu: [
                    //         {
                    //             id: 1312,
                    //             url: "dam/parameters/systemParameters/capacityRightTemplate",
                    //             name: `Capacity Right Template`,
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpbktp"],
                    //             keywords: "dpbktp",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Capacity Right Template",
                    //             menus_config_id: 42,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1302,
                    //             url: "dam/parameters/systemParameters/planningDeadline",
                    //             name: "Planning Deadline",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dppd"],
                    //             keywords: "dppd",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Planning Deadline",
                    //             menus_config_id: 32,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1301,
                    //             url: "dam/parameters/systemParameters/nominationDeadline",
                    //             name: "Nomination Deadline",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpde"],
                    //             keywords: "dpde",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Nomination Deadline",
                    //             menus_config_id: 31,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1305,
                    //             url: "dam/parameters/systemParameters/emailNotiManage",
                    //             name: "Email Notification Management",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpenmgn"],
                    //             keywords: "dpenmgn",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Email Notification Management",
                    //             menus_config_id: 35,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1315,
                    //             url: "dam/parameters/systemParameters/emailGroupForEvent",
                    //             name: `Email Group For Event`,
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpegfe"],
                    //             keywords: "dpegfe",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Email Group For Event",
                    //             menus_config_id: 1006,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1304,
                    //             url: "dam/parameters/systemParameters/systemParameter",
                    //             name: "System Parameter",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpsp"],
                    //             keywords: "dpsp",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > System Parameter",
                    //             menus_config_id: 34,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1318,
                    //             url: "dam/parameters/systemParameters/allocationMode",
                    //             name: "Allocation Mode",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpspallocmode"],
                    //             keywords: "dpspallocmode",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Allocation Mode",
                    //             menus_config_id: 1007,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1319,
                    //             url: "dam/parameters/systemParameters/hvOperationFlow",
                    //             name: "HV for Operation Flow and Instructed Flow",
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpsphv"],
                    //             keywords: "dpsphv",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > HV for Operation Flow and Instructed Flow",
                    //             menus_config_id: 1008,
                    //             menu: [],
                    //         },
                    //         {
                    //             id: 1313,
                    //             url: "dam/parameters/systemParameters/configModeZoneBaseInven",
                    //             name: `Config Mode/Zone Base Inventory`,
                    //             icon: null,
                    //             active: true,
                    //             toggle: false,
                    //             shortcut: ["dpcgmdznba"],
                    //             keywords: "dpcgmdznba",
                    //             section: "Dam",
                    //             subtitle: "DAM > Parameters > System Parameter > Config Mode/Zone Base Inventory",
                    //             menus_config_id: 1009,
                    //             menu: [],
                    //         },
                    //     ],
                    // },
                    { // เปลี่ยนชื่อเมนู System Parameter  เป็น System Configuration https://app.clickup.com/t/86eub6d1b
                        id: 1317,
                        url: "dam/parameters/systemConfiguration",
                        name: "System Configuration",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpsyspa"],
                        keywords: "dpsyspa",
                        section: "Parameters",
                        subtitle: "DAM > Parameters > System Configuration",
                        menus_config_id: 1005,
                        menu: [
                            {
                                id: 1312,
                                url: "dam/parameters/systemConfiguration/capacityRightTemplate",
                                name: `Capacity Right Template`,
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpbktp"],
                                keywords: "dpbktp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Capacity Right Template",
                                menus_config_id: 42,
                                menu: [],
                            },
                            {
                                id: 1302,
                                url: "dam/parameters/systemConfiguration/planningDeadline",
                                name: "Planning Deadline",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dppd"],
                                keywords: "dppd",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Planning Deadline",
                                menus_config_id: 32,
                                menu: [],
                            },
                            {
                                id: 1301,
                                url: "dam/parameters/systemConfiguration/nominationDeadline",
                                name: "Nomination Deadline",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpde"],
                                keywords: "dpde",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Nomination Deadline",
                                menus_config_id: 31,
                                menu: [],
                            },
                            {
                                id: 1305,
                                url: "dam/parameters/systemConfiguration/emailNotiManage",
                                name: "Email Notification Management",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpenmgn"],
                                keywords: "dpenmgn",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Email Notification Management",
                                menus_config_id: 35,
                                menu: [],
                            },
                            {
                                id: 1315,
                                url: "dam/parameters/systemConfiguration/emailGroupForEvent",
                                name: `Email Group For Event`,
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpegfe"],
                                keywords: "dpegfe",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Email Group For Event",
                                menus_config_id: 1006,
                                menu: [],
                            },
                            {
                                id: 1304,
                                url: "dam/parameters/systemConfiguration/systemParameter",
                                name: "System Parameter",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpsp"],
                                keywords: "dpsp",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > System Parameter",
                                menus_config_id: 34,
                                menu: [],
                            },
                            {
                                id: 1318,
                                url: "dam/parameters/systemConfiguration/allocationMode",
                                name: "Allocation Mode",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpspallocmode"],
                                keywords: "dpspallocmode",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Allocation Mode",
                                menus_config_id: 1007,
                                menu: [],
                            },
                            {
                                id: 1319,
                                url: "dam/parameters/systemConfiguration/hvOperationFlow",
                                name: "HV for Operation Flow and Instructed Flow",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpsphv"],
                                keywords: "dpsphv",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > HV for Operation Flow and Instructed Flow",
                                menus_config_id: 1008,
                                menu: [],
                            },
                            {
                                id: 1313,
                                url: "dam/parameters/systemConfiguration/configModeZoneBaseInven",
                                name: `Config Mode/Zone Base Inventory`,
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpcgmdznba"],
                                keywords: "dpcgmdznba",
                                section: "Dam",
                                subtitle: "DAM > Parameters > System Configuration > Config Mode/Zone Base Inventory",
                                menus_config_id: 1009,
                                menu: [],
                            },
                        ],
                    },
                    {
                        id: 1320,
                        url: "dam/parameters/uxui",
                        name: "UX/UI",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["dpuxui"],
                        keywords: "dpuxui",
                        section: "Parameters",
                        subtitle: "DAM > Parameters > UX/UI",
                        menus_config_id: 1004,
                        menu: [
                            {
                                id: 1306,
                                url: "dam/parameters/uxui/userGuide",
                                name: "User Guide",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpug"],
                                keywords: "dpug",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > User Guide",
                                menus_config_id: 36,
                                menu: [],
                            },
                            {
                                id: 1311,
                                url: "dam/parameters/uxui/meteringCheckingCondition",
                                name: `Metering Checking Condition`,
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpmechkcon"],
                                keywords: "dpmechkcon",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > Metering Checking Condition",
                                menus_config_id: 33,
                                menu: [],
                            },
                            {
                                id: 1308,
                                url: "dam/parameters/uxui/capacityPublicRemarks",
                                name: "Capacity Publication Remarks",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpcappubrem"],
                                keywords: "dpcappubrem",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > Capacity Publication Remarks",
                                menus_config_id: 40,
                                menu: [],
                            },
                            {
                                id: 1303,
                                url: "dam/parameters/uxui/announcement",
                                name: "Announcement",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpan"],
                                keywords: "dpan",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > Announcement",
                                menus_config_id: 38,
                                menu: [],
                            },
                            {
                                id: 1310,
                                url: "dam/parameters/uxui/termAndCondition",
                                name: `Terms & Conditions`,
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dptandc"],
                                keywords: "dptandc",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > Terms & Conditions",
                                menus_config_id: 39,
                                menu: [],
                            },
                            {
                                id: 1309,
                                url: "dam/parameters/uxui/setupBackground",
                                name: "Main Menu Background",
                                icon: null,
                                active: true,
                                toggle: false,
                                shortcut: ["dpsetbg"],
                                keywords: "dpsetbg",
                                section: "Dam",
                                subtitle: "DAM > Parameters > UX/UI > Main Menu Background",
                                menus_config_id: 43,
                                menu: [],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: 101,
        url: "booking",
        name: "Capacity Management",
        icon: <BookOutlinedIcon />,
        iconSize: <BookOutlinedIcon className="!text-[30px] md:!text-[45px] lg:!text-[57px]" />,
        active: true,
        toggle: false,
        shortcut: ["b"],
        keywords: "b",
        section: "Capacity Management",
        subtitle: "Capacity Management",
        menus_config_id: 49,
        menu: [
            {
                id: 2001,
                url: "booking/bulletinBoard",
                name: "Bulletin Board",
                icon: <BorderAllOutlinedIcon />,
                iconSize: <BorderAllOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkblb"],
                keywords: "bkblb",
                section: "Capacity Management",
                subtitle: "Capacity Management > Bulletin Board",
                menus_config_id: 52,
                menu: []
            },
            {
                id: 2003,
                url: "booking/capacity",
                name: "Capacity",
                icon: <WaterDropRoundedIcon />,
                iconSize: <WaterDropRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkcap"],
                keywords: "bkcap",
                section: "Capacity Management",
                subtitle: "Capacity Management > Capacity",
                // menus_config_id: 49,
                menus_config_id: 1010,
                menu: [
                    {
                        id: 200302,
                        url: "booking/capacity/CapPublication",
                        name: "Capacity Publication",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcappub"],
                        keywords: "bkcappub",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Capacity > Capacity Publication",
                        menus_config_id: 54,
                        menu: [],
                    },
                    {
                        id: 200303,
                        url: "booking/capacity/CapacityChart",
                        name: "Capacity Chart",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcapchart"],
                        keywords: "bkcapchart",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Capacity > Capacity Chart",
                        menus_config_id: 55,
                        menu: [],
                    },
                    {
                        id: 200301,
                        url: "booking/capacity/CapReqMgn",
                        name: "Capacity Contract Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcapreqmgn"],
                        keywords: "bkcapreqmgn",
                        section: "Capacity Management",
                        // subtitle: "Booking > Capacity > Capacity Request Management",
                        subtitle: "Capacity Management > Capacity > Capacity Contract Management",
                        menus_config_id: 50,
                        menu: [],
                    },
                    {
                        id: 200304,
                        url: "booking/capacity/CapContractList",
                        name: "Capacity Contract List",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkcontlist"],
                        keywords: "bkcontlist",
                        section: "Capacity Management",
                        // subtitle: "Booking > Capacity > Capacity Request Management",
                        subtitle: "Capacity Management > Capacity > Capacity Contract List",
                        menus_config_id: 53,
                        menu: [],
                    },

                ]
            },
            {
                id: 2004,
                url: "booking/release",
                name: "Release",
                icon: <OpacityRoundedIcon />,
                iconSize: <OpacityRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkrel"],
                keywords: "bkrel",
                section: "Capacity Management",
                subtitle: "Capacity Management > Release",
                // menus_config_id: 49,
                menus_config_id: 1011,
                menu: [
                    {
                        id: 200401,
                        url: "booking/release/ReleaseCapSubmission",
                        name: "Release Capacity Submission",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelcapsub"],
                        keywords: "bkrelcapsub",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release Capacity Submission",
                        menus_config_id: 56,
                        menu: [],
                    },
                    {
                        id: 200402,
                        url: "booking/release/ReleaseCapManagement",
                        name: "Release Capacity Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelcapmgn"],
                        keywords: "bkrelcapmgn",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release Capacity Management",
                        menus_config_id: 60,
                        menu: [],
                    },
                    {
                        id: 200403,
                        url: "booking/release/ReleaseSumManagement",
                        name: "Release/UIOLI Summary Management",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["bkrelsummgn"],
                        keywords: "bkrelsummgn",
                        section: "Capacity Management",
                        subtitle: "Capacity Management  > Release > Release/UIOLI Summary Management",
                        menus_config_id: 58,
                        menu: [],
                    },
                ]
            },
            {
                id: 2005,
                url: "booking/useItOrLoseIt",
                name: "Use It or Lose It",
                icon: <RepeatOutlinedIcon />,
                iconSize: <RepeatOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkuioli"],
                keywords: "bkuioli",
                section: "Capacity Management",
                subtitle: "Capacity Management > Use It or Lose It",
                menus_config_id: 57,
                menu: []
            },
            {
                id: 2006,
                url: "booking/reserveBalGasContracts",
                name: "Reserve Balancing Gas Contracts",
                icon: <BallotOutlinedIcon />,
                iconSize: <BallotOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkresbalgascon"],
                keywords: "bkresbalgascon",
                section: "Capacity Management",
                subtitle: "Capacity Management > Reserve Balancing Gas Contracts ",
                menus_config_id: 59,
                menu: []
            },
            {
                id: 2002,
                url: "booking/pathManagement",
                name: "Path Management",
                icon: <TimelineRoundedIcon />,
                iconSize: <TimelineRoundedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["bkpmgn"],
                keywords: "bkpmgn",
                section: "Capacity Management",
                subtitle: "Capacity Management > Path Management",
                menus_config_id: 51,
                menu: []
            },
        ],
    },
    {
        id: 201,
        url: "allocation",
        name: "Allocation",
        icon: <CalculateOutlinedIcon />,
        iconSize: <CalculateOutlinedIcon className="!text-[35px] md:!text-[50px] lg:!text-[65px]" />,
        active: true,
        toggle: false,
        shortcut: ["al"],
        keywords: "al",
        section: "Allocation",
        subtitle: "Allocation",
        menus_config_id: 80,
        menu: [
            {
                id: 2001,
                url: "allocation/allocationReview",
                name: "Allocation Review",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alre"],
                keywords: "alre",
                section: "Allocation",
                subtitle: "Allocation > Allocation Review",
                menus_config_id: 81,
                menu: []
            },
            {
                id: 2002,
                url: "allocation/alloManage",
                name: "Allocation Management",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alma"],
                keywords: "alma",
                section: "Allocation",
                subtitle: "Allocation > Allocation Management",
                menus_config_id: 82,
                menu: []
            },
            {
                id: 2003,
                url: "allocation/alloQuery",
                name: "Allocation Query",
                icon: <FeaturedPlayListOutlinedIcon />,
                iconSize: <FeaturedPlayListOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alque"],
                keywords: "alque",
                section: "Allocation",
                subtitle: "Allocation > Allocation Query",
                menus_config_id: 83,
                menu: []
            },
            {
                id: 2004,
                url: "allocation/alloReport",
                name: "Allocation Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alrep"],
                keywords: "alrep",
                section: "Allocation",
                subtitle: "Allocation > Allocation Report",
                menus_config_id: 84,
                menu: []
            },
            {
                id: 2005,
                url: "allocation/allocationMonthlyReport",
                name: "Allocation Monthly Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["almorep"],
                keywords: "almorep",
                section: "Allocation",
                subtitle: "Allocation > Allocation Monthly Report",
                menus_config_id: 86,
                menu: []
            },
            {
                id: 2006,
                url: "allocation/curtailmentsAllocation",
                name: "Curtailments Allocation",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alcurrep"],
                keywords: "alcurrep",
                section: "Allocation",
                subtitle: "Allocation > Curtailments Allocation",
                menus_config_id: 85,
                menu: []
            },
            {
                id: 2007,
                url: "allocation/allocShipperReport",
                name: "Allocation Shipper Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["alcurrep"],
                keywords: "alcurrep",
                section: "Allocation",
                subtitle: "Allocation > Allocation Shipper Report",
                menus_config_id: 1017,
                menu: []
            },
        ],
    },
    {
        id: 301,
        url: "balancing",
        name: "Balancing",
        icon: <EqualizerOutlinedIcon />,
        iconSize: <EqualizerOutlinedIcon className="!text-[40px] md:!text-[60px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        // shortcut: ["al"],
        // keywords: "al",
        section: "Balancing",
        subtitle: "Balancing",
        menus_config_id: 87,
        menu: [
            {
                id: 3001,
                url: "balancing/balIntradayDashboard",
                name: "Intraday Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balindash"],
                keywords: "balindash",
                section: "Balancing",
                subtitle: "Balancing > Intraday Dashboard",
                menus_config_id: 90,
                menu: []
            },
            {
                id: 3014,
                url: "balancing/balIntraDashboardForShipper",
                name: "Intraday Dashboard for Shipper",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balindashshipper"],
                keywords: "balindashshipper",
                section: "Balancing",
                subtitle: "Balancing > Intraday Dashboard for Shipper",
                menus_config_id: 1020,
                menu: []
            },
            {
                id: 3002,
                url: "balancing/balOperateFlowAndInstructedFlow",
                name: "Operation Flow and Instructed Flow",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["baloperateflow"],
                keywords: "baloperateflow",
                section: "Balancing",
                subtitle: "Balancing > Operation Flow and Instructed Flow",
                menus_config_id: 89,
                menu: []
            },
            {
                id: 3003,
                url: "balancing/balReport",
                name: "Balance Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balreport"],
                keywords: "balreport",
                section: "Balancing",
                subtitle: "Balancing > Balance Report",
                menus_config_id: 94,
                menu: []
            },
            {
                id: 3004,
                url: "balancing/closedBalancingReport",
                name: "Closed Balancing Report",
                icon: <ChromeReaderModeOutlinedIcon />,
                iconSize: <ChromeReaderModeOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balmgn"],
                keywords: "balmgn",
                section: "Balancing",
                subtitle: "Balancing > Closed Balancing Report",
                menus_config_id: 91,
                menu: []
            },
            {
                id: 3005,
                url: "balancing/intradayBalReport",
                name: "Intraday Balancing Report",
                icon: <ChromeReaderModeOutlinedIcon />,
                iconSize: <ChromeReaderModeOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbalrep"],
                keywords: "balinbalrep",
                section: "Balancing",
                subtitle: "Balancing > Intraday Balancing Report",
                menus_config_id: 93,
                menu: []
            },
            {
                id: 3006,
                url: "balancing/balIntraBalReportForShipper",
                name: "Intraday Balancing Report For Shipper",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbalrepshp"],
                keywords: "balinbalrepshp",
                section: "Balancing",
                subtitle: "Balancing > Intraday Balancing Report For Shipper ",
                menus_config_id: 92,
                menu: []
            },
            {
                id: 3007,
                url: "balancing/intradayAccImbalanceInventory",
                name: "Intraday Acc. Imbalance inventory",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinacciminven"],
                keywords: "balinacciminven",
                section: "Balancing",
                subtitle: "Balancing > Intraday Acc. Imbalance inventory",
                // menus_config_id: 95,
                menus_config_id: 1019,
                menu: []
            },
            {
                id: 3008,
                url: "balancing/intradayBaseInventory",
                name: "Intraday Base Inventory",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbaseinven"],
                keywords: "balinbaseinven",
                section: "Balancing",
                subtitle: "Balancing > Intraday Base Inventory",
                menus_config_id: 96,
                menu: []
            },
            {
                id: 3013,
                url: "balancing/intraBaseInventoryShipper",
                name: "Intraday Base Inventory Shipper",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balinbaseinvenshipper"],
                keywords: "balinbaseinvenshipper",
                section: "Balancing",
                subtitle: "Balancing > Intraday Base Inventory Shipper",
                menus_config_id: 1016,
                menu: []
            },
            {
                id: 3009,
                url: "balancing/ventCommissioningOtherGas",
                name: "Vent/Commissioning/Other Gas ",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balventcomothgas"],
                keywords: "balventcomothgas",
                section: "Balancing",
                subtitle: "Balancing > Vent/Commissioning/Other Gas ",
                menus_config_id: 88,
                menu: []
            },
            // {
            //     id: 3010,
            //     url: "balancing/balVenComOthGas",
            //     name: "Vent/Commissioning/Other Gas",
            //     icon: <RateReviewOutlinedIcon />,
            //     iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
            //     active: true,
            //     toggle: false,
            //     shortcut: ["balventcomothgas"],
            //     keywords: "balventcomothgas",
            //     section: "Balancing",
            //     subtitle: "Balancing > Vent/Commissioning/Other Gas",
            //     menus_config_id: 88,
            //     menu: []
            // },
            {
                id: 3011,
                url: "balancing/balAdjust",
                name: "Adjustment",
                icon: <WebAssetOutlinedIcon />,
                iconSize: <WebAssetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["baladjust"],
                keywords: "baladjust",
                section: "Balancing",
                subtitle: "Balancing > Adjustment",
                menus_config_id: 98,
                menu: [
                    {
                        id: 30111,
                        url: "balancing/balAdjust/intradayAccImbalanceInventoryAdjust",
                        name: "Intraday Acc. Imbalance Inventory Adjust",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjintraaccim"],
                        keywords: "baladjintraaccim",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Intraday Acc. Imbalance Inventory Adjust",
                        menus_config_id: 99,
                        menu: [],
                    },
                    {
                        id: 30112,
                        url: "balancing/balAdjust/adjustmentDailyImbalance",
                        name: "Adjustment Daily Imbalance",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjdailimbal"],
                        keywords: "baladjdailimbal",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Adjustment Daily Imbalance",
                        menus_config_id: 100,
                        menu: [],
                    },
                    {
                        id: 30113,
                        url: "balancing/balAdjust/adjustAccumulatedImbalance",
                        name: "Adjust Accumulated Imbalance",
                        icon: null,
                        active: true,
                        toggle: false,
                        shortcut: ["baladjimbalalloc"],
                        keywords: "baladjimbalalloc",
                        section: "Balancing",
                        subtitle: "Balancing > Adjustment > Adjust Accumulated Imbalance",
                        menus_config_id: 101,
                        menu: [],
                    },
                ],
            },
            {
                id: 3012,
                url: "balancing/balSystemAccImbInv",
                name: "System Acc. Imbalance Inventory",
                icon: <EqualizerOutlinedIcon />,
                iconSize: <EqualizerOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balsysacc"],
                keywords: "balsysacc",
                section: "Balancing",
                subtitle: "Balancing > System Acc. IMB.",
                menus_config_id: 97,
                menu: []
            },
             {
                id: 3013,
                url: "balancing/balIntraAccImbDashboard",
                name: "Intraday Acc. Imbalance Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balintradayaccimbdashboard"],
                keywords: "balintradayaccimbdashboard",
                section: "Balancing",
                subtitle: "Balancing > Intraday Acc. Imbalance Dashboard",
                menus_config_id: 95,
                menu: []
            },
            {
                id: 3014,
                url: "balancing/balMonthlyReport",
                name: "Balance Monthly Report",
                icon: <RateReviewOutlinedIcon />,
                iconSize: <RateReviewOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["balmonthlyreport"],
                keywords: "balmonthlyreport",
                section: "Balancing",
                subtitle: "Balancing > Balance Monthly Report",
                menus_config_id: 1018,
                menu: []
            }
        ]
    },
    {
        id: 401,
        url: "pmis.pipeline.pttplc.com/smartTSO/login.php",
        name: "PMIS Graphics",
        icon: <DonutSmallOutlinedIcon />,
        iconSize: <DonutSmallOutlinedIcon className="!text-[40px] md:!text-[60px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "PMIS Graphics",
        subtitle: "PMIS Graphics",
        menus_config_id: 1026,
        menu: []
    },
    {
        id: 501,
        url: "planning",
        name: "Planning",
        icon: <TrendingUpOutlinedIcon />,
        iconSize: <TrendingUpOutlinedIcon className="!text-[40px] md:!text-[60px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Planning",
        subtitle: "Planning",
        menus_config_id: 44,
        menu: [
            {
                id: 5001,
                url: "planning/planningDashboard",
                name: "Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plndash"],
                keywords: "plndash",
                section: "Planning",
                subtitle: "Planning > Planning Dashboard",
                // menus_config_id: 45,
                menus_config_id: 1015,
                menu: []
            },
            {
                id: 5005,
                url: "planning/planningFileSubmissionTemplate",
                name: "Planning File Submission Template",
                icon: <PermContactCalendarOutlinedIcon />,
                iconSize: <PermContactCalendarOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnfilesubtemp"],
                keywords: "plnfilesubtemp",
                section: "Planning",
                subtitle: "Planning > Planning File Submission Template",
                // menus_config_id: 1001,
                menus_config_id: 45,
                menu: []
            },
            {
                id: 5003,
                url: "planning/planningSubmissionFiles",
                name: "Planning Submission File",
                icon: <BorderAllOutlinedIcon />,
                iconSize: <BorderAllOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnsubfile"],
                keywords: "plnsubfile",
                section: "Planning",
                subtitle: "Planning > Planning Submission File",
                menus_config_id: 47,
                menu: []
            },
            {
                id: 5002,
                url: "planning/planningQueryShipperFiles",
                name: "Query Shippers' Planning Files",
                icon: <InsertDriveFileOutlinedIcon />,
                iconSize: <InsertDriveFileOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnqueshpfile"],
                keywords: "plnqueshpfile",
                section: "Planning",
                subtitle: "Planning > Query Shippers' Planning Files",
                menus_config_id: 46,
                menu: []
            },
            {
                id: 5004,
                url: "planning/planningNewPoint",
                name: "New Point",
                icon: <NoteAddOutlinedIcon />,
                iconSize: <NoteAddOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["plnnewpoint"],
                keywords: "plnnewpoint",
                section: "Planning",
                subtitle: "Planning > New Point",
                menus_config_id: 48,
                menu: []
            },
        ]
    },
    {
        id: 601,
        url: "nominations",
        name: "Nominations",
        icon: <TextSnippetOutlinedIcon />,
        iconSize: <TextSnippetOutlinedIcon className="!text-[40px] md:!text-[57px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Nominations",
        subtitle: "Nominations",
        menus_config_id: 61,
        menu: [
            {
                id: 6001,
                url: "nominations/nominationsDashboard",
                name: "Nominations Dashboard",
                icon: <DashboardOutlinedIcon />,
                iconSize: <DashboardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdash"],
                keywords: "nomdash",
                section: "Nominations",
                subtitle: "Nominations > Nominations Dashboard",
                menus_config_id: 62,
                menu: []
            },
            {
                id: 6002,
                url: "nominations/submissionFile",
                name: "Submission File",
                icon: <InsertDriveFileOutlinedIcon />,
                iconSize: <InsertDriveFileOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomsubfile"],
                keywords: "nomsubfile",
                section: "Nominations",
                subtitle: "Nominations > Submission File",
                menus_config_id: 63,
                menu: []
            },
            {
                id: 6003,
                url: "nominations/queryShipperNominationFile",
                name: "Query Shipper Nomination File",
                icon: <InsertDriveFileOutlinedIcon />,
                iconSize: <InsertDriveFileOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomqueryshipperfile"],
                keywords: "nomqueryshipperfile",
                section: "Nominations",
                subtitle: "Nominations > Query Shipper Nomination File",
                menus_config_id: 64,
                menu: []
            },
            {
                id: 6004,
                url: "nominations/dailyManagement",
                name: "Daily Management",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdailymgn"],
                keywords: "nomdailymgn",
                section: "Nominations",
                subtitle: "Nominations > Daily Management",
                menus_config_id: 65,
                menu: []
            },
            {
                id: 6005,
                url: "nominations/dailyAdjustment",
                name: "Daily Adjustment",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdailyadj"],
                keywords: "nomdailyadj",
                section: "Nominations",
                subtitle: "Nominations > Daily Adjustment",
                menus_config_id: 68,
                menu: []
            },
            {
                id: 6006,
                url: "nominations/dailyadjustmentSummary",
                name: "Daily Adjustment Summary",
                icon: <ImageAspectRatioOutlinedIcon />,
                iconSize: <ImageAspectRatioOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdailadjsum"],
                keywords: "nomdailadjsum",
                section: "Nominations",
                subtitle: "Nominations > Daily Adjustment Summary",
                menus_config_id: 69,
                menu: []
            },
            {
                id: 6007,
                url: "nominations/daiAdjustmentReport",
                name: "Daily Adjustment Report",
                icon: <ImageAspectRatioOutlinedIcon />,
                iconSize: <ImageAspectRatioOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdailadjreport"],
                keywords: "nomdailadjreport",
                section: "Nominations",
                subtitle: "Nominations > Daily Adjustment Report",
                menus_config_id: 1012,
                menu: []
            },
            {
                id: 6008,
                url: "nominations/weeklyManagement",
                name: "Weekly Management",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomweekmgn"],
                keywords: "nomweekmgn",
                section: "Nominations",
                subtitle: "Nominations > Weekly Management",
                menus_config_id: 66,
                menu: []
            },
            {
                id: 6009,
                url: "nominations/shipperNominationReport",
                name: "Shipper Nomination Report",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomshipperreport"],
                keywords: "nomshipperreport",
                section: "Nominations",
                subtitle: "Nominations > Shipper Nomination Report",
                menus_config_id: 67,
                menu: []
            },
            {
                id: 6010,
                url: "nominations/parkingAllocation",
                name: "Parking Allocation",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdash"],
                keywords: "nomdash",
                section: "Nominations",
                subtitle: "Nominations > Parking Allocation",
                menus_config_id: 70,
                menu: []
            },
            {
                id: 6011,
                url: "nominations/uploadTemplateForShipper",
                name: "Upload template for shipper",
                icon: <UploadOutlinedIcon />,
                iconSize: <UploadOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomuptempforshipper"],
                keywords: "nomuptempforshipper",
                section: "Nominations",
                subtitle: "Nominations > Upload template for shipper",
                menus_config_id: 71,
                menu: []
            },
            {
                id: 6012,
                url: "nominations/qualityPlanning",
                name: "Quality Planning",
                icon: <VerifiedOutlinedIcon />,
                iconSize: <VerifiedOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomqualityplanning"],
                keywords: "nomqualityplanning",
                section: "Nominations",
                subtitle: "Nominations > Quality Planning",
                menus_config_id: 72,
                menu: []
            },
            {
                id: 6013,
                url: "nominations/qualityEvaluation",
                name: "Quality Evaluation",
                icon: <VerifiedOutlinedIcon />,
                iconSize: <VerifiedOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomqualityevalua"],
                keywords: "nomqualityevalua",
                section: "Nominations",
                subtitle: "Nominations > Quality Evaluation",
                menus_config_id: 73,
                menu: []
            },
            {
                id: 6014,
                url: "nominations/summaryNominationReport",
                name: "Summary Nomination Report",
                icon: <ImageAspectRatioOutlinedIcon />,
                iconSize: <ImageAspectRatioOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdash"],
                keywords: "nomdash",
                section: "Nominations",
                subtitle: "Nominations > Summary Nomination Report",
                menus_config_id: 74,
                menu: []
            },
            {
                id: 6015,
                url: "nominations/minimumInventorySummary",
                name: "Minimum Inventory Summary",
                icon: <ImageAspectRatioOutlinedIcon />,
                iconSize: <ImageAspectRatioOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["nomdash"],
                keywords: "nomdash",
                section: "Nominations",
                subtitle: "Nominations > Minimum Inventory Summary",
                menus_config_id: 75,
                menu: []
            },
        ]
    },
    {
        id: 701,
        url: "metering",
        name: "Metering",
        icon: <TableViewIcon />,
        iconSize: <TableViewIcon className="!text-[40px] md:!text-[57px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Metering",
        subtitle: "Metering",
        menus_config_id: 76,
        menu: [
            {
                id: 7001,
                url: "metering/MeteringManagement",
                name: "Metering Management",
                icon: <SettingsOutlinedIcon />,
                iconSize: <SettingsOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["metermgn"],
                keywords: "metermgn",
                section: "Metering",
                subtitle: "Metering > Metering Management",
                menus_config_id: 77,
                menu: []
            },
            {
                id: 7002,
                url: "metering/MeteringRetrieving",
                name: "Metering Retrieving",
                icon: <ReportProblemOutlinedIcon />,
                iconSize: <ReportProblemOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["meterretriev"],
                keywords: "meterretriev",
                section: "Metering",
                subtitle: "Metering > Metering Retrieving",
                menus_config_id: 78,
                menu: []
            },
            {
                id: 7003,
                url: "metering/MeteringChecking",
                name: "Metering Checking",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["metercheck"],
                keywords: "metercheck",
                section: "Metering",
                subtitle: "Metering > Metering Checking",
                menus_config_id: 79,
                menu: []
            },
        ]
    },
    {
        id: 801,
        url: "event",
        name: "Event",
        icon: <CalendarTodayOutlinedIcon />,
        iconSize: <CalendarTodayOutlinedIcon className="!text-[40px] md:!text-[57px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Event",
        subtitle: "Event",
        menus_config_id: 105,
        menu: [
            {
                id: 8001,
                url: "event/EventOffSpecGas",
                name: "Offspec Gas",
                icon: <WaterDropSharpIcon />,
                iconSize: <WaterDropSharpIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["eventoffspecgas"],
                keywords: "eventoffspecgas",
                section: "Event",
                subtitle: "Event > Offspec Gas",
                menus_config_id: 107,
                menu: []
            },
            {
                id: 8002,
                url: "event/EmergencyDifficultDay",
                name: "Emergency/Difficult Day",
                icon: <WarningAmberOutlinedIcon />,
                iconSize: <WarningAmberOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["eventoffspecgas"],
                keywords: "eventoffspecgas",
                section: "Event",
                subtitle: "Event > Emergency/Difficult Day",
                menus_config_id: 106,
                menu: []
            },
            {
                id: 8003,
                url: "event/OFIF",
                name: "OF/IF",
                icon: <SwapHorizontalCircleOutlinedIcon />,
                iconSize: <SwapHorizontalCircleOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["eventoffspecgas"],
                keywords: "eventoffspecgas",
                section: "Event",
                subtitle: "Event > OF/IF",
                menus_config_id: 1013,
                menu: []
            },
        ]
    },
    {
        id: 901,
        url: "tariff",
        name: "Tariff",
        icon: <PaymentsOutlinedIcon />,
        iconSize: <PaymentsOutlinedIcon className="!text-[40px] md:!text-[57px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Tariff",
        subtitle: "Tariff",
        menus_config_id: 102,
        menu: [
            {
                id: 9001,
                url: "tariff/TariffChargeReport",
                name: "Tariff Charge Report",
                icon: <TextSnippetOutlinedIcon />,
                iconSize: <TextSnippetOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["tariffchargereport"],
                keywords: "tariffchargereport",
                section: "Tariff",
                subtitle: "Tariff > Tariff Charge Report",
                menus_config_id: 103,
                menu: []
            },
            {
                id: 9002,
                url: "tariff/TariffCreditDebitNote",
                name: "Credit/Debit Note",
                icon: <CreditCardOutlinedIcon />,
                iconSize: <CreditCardOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["tariffcreditdebitnote"],
                keywords: "tariffcreditdebitnote",
                section: "Tariff",
                subtitle: "Tariff > Credit/Debit Note",
                menus_config_id: 104,
                menu: []
            },
        ]
    },
    {
        id: 1001,
        url: "dashboardandreport",
        name: "Dashboard & Report",
        icon: <PieChartOutlineOutlinedIcon />,
        iconSize: <PieChartOutlineOutlinedIcon className="!text-[40px] md:!text-[57px] lg:!text-[68px]" />,
        active: true,
        toggle: false,
        section: "Dashboard & Report",
        subtitle: "Dashboard & Report",
        menus_config_id: 1001,
        menu: [
            {
                id: 10001,
                url: "dashboardandreport/waitinglist",
                name: "Waiting List",
                icon: <ViewAgendaOutlinedIcon />,
                iconSize: <ViewAgendaOutlinedIcon style={{ fontSize: "72px" }} />,
                active: true,
                toggle: false,
                shortcut: ["waitinglist"],
                keywords: "waitinglist",
                section: "Dashboard & Report",
                subtitle: "Dashboard & Report > Waiting List",
                menus_config_id: 1014,
                menu: []
            }
        ]
    }
    // {
    //   id: 9999,
    //   url: "temp",
    //   name: "Temp",
    //   icon: <GroupIcon />,
    //   iconSize: <GroupIcon style={{ fontSize:"72px" }} />,
    //   active: true,
    //   toggle: false,
    //   shortcut: ["t"],
    //   keywords: "t",
    //   section: "Temp",
    //   subtitle: "Temp",
    //   menu: [],
    // },
]