export const dataMock = [
    {
        "id": 15,
        "name": "EAST-ZONE-4",
        "color": "#ff9500",
        "create_date": "2024-09-24T17:57:50.584Z",
        "update_date": null,
        "create_date_num": 1727175470,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": "test 4",
        "start_date": "2024-09-27T00:00:00.000Z",
        "end_date": "2024-10-09T00:00:00.000Z",
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 9,
                "name": null,
                "create_date": "2024-09-24T17:57:50.735Z",
                "update_date": "2024-09-24T17:57:51.129Z",
                "create_date_num": 1727175470,
                "update_date_num": 1727175471,
                "create_by": 1,
                "update_by": 1,
                "active": true,
                "c1_min": 2,
                "c1_max": 3,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": 4,
                "wobbe_index_max": 5,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": 6.124,
                "sg_max": 9,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 15
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 14,
        "name": "EAST-KOM-3",
        "color": null,
        "create_date": "2024-09-24T17:14:21.131Z",
        "update_date": null,
        "create_date_num": 1727172861,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": "test 3",
        "start_date": "2024-09-08T00:00:00.000Z",
        "end_date": "2025-06-19T00:00:00.000Z",
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 8,
                "name": null,
                "create_date": "2024-09-24T17:14:21.228Z",
                "update_date": "2024-09-24T17:14:21.594Z",
                "create_date_num": 1727172861,
                "update_date_num": 1727172861,
                "create_by": 1,
                "update_by": 1,
                "active": true,
                "c1_min": 1.44,
                "c1_max": 2.44,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": 3.55,
                "wobbe_index_max": 6.66,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": null,
                "sg_max": null,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 14
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 13,
        "name": "EAST-KOM-2",
        "color": null,
        "create_date": "2024-09-24T17:12:38.737Z",
        "update_date": null,
        "create_date_num": 1727172758,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": "test 2",
        "start_date": "2024-09-26T00:00:00.000Z",
        "end_date": "2025-02-13T00:00:00.000Z",
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 7,
                "name": null,
                "create_date": "2024-09-24T17:12:38.833Z",
                "update_date": "2024-09-24T17:12:39.160Z",
                "create_date_num": 1727172758,
                "update_date_num": 1727172759,
                "create_by": 1,
                "update_by": 1,
                "active": true,
                "c1_min": null,
                "c1_max": null,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": null,
                "wobbe_index_max": null,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": null,
                "sg_max": null,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 13
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 12,
        "name": "east-kom-1",
        "color": null,
        "create_date": "2024-09-24T17:10:28.689Z",
        "update_date": null,
        "create_date_num": 1727172628,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": "test",
        "start_date": "2024-09-12T00:00:00.000Z",
        "end_date": "2024-09-28T00:00:00.000Z",
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 6,
                "name": null,
                "create_date": "2024-09-24T17:10:28.816Z",
                "update_date": null,
                "create_date_num": 1727172628,
                "update_date_num": null,
                "create_by": 1,
                "update_by": null,
                "active": true,
                "c1_min": null,
                "c1_max": null,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": null,
                "wobbe_index_max": null,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": null,
                "sg_max": null,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 12
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 11,
        "name": "EAST - DEMO",
        "color": "#FF0000",
        "create_date": "2024-09-24T16:30:55.535Z",
        "update_date": "2024-09-24T16:36:15.118Z",
        "create_date_num": 1727170255,
        "update_date_num": 1727170575,
        "create_by": 1,
        "update_by": 1,
        "description": null,
        "start_date": "2024-09-10T03:10:10.000Z",
        "end_date": null,
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 5,
                "name": null,
                "create_date": "2024-09-24T16:30:55.645Z",
                "update_date": "2024-09-24T16:37:37.928Z",
                "create_date_num": 1727170255,
                "update_date_num": 1727170657,
                "create_by": 1,
                "update_by": 1,
                "active": true,
                "c1_min": 10.99,
                "c1_max": null,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": null,
                "wobbe_index_max": null,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": null,
                "sg_max": null,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 11
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        }
    },
    {
        "id": 6,
        "name": "East - West",
        "color": "#C8FFD7",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": null,
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 2,
        "zone_master_quality": [],
        "entry_exit": {
            "id": 2,
            "name": "Exit",
            "color": "#FFF3C8"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 5,
        "name": "West",
        "color": "#FFCEE2",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": null,
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 2,
        "zone_master_quality": [],
        "entry_exit": {
            "id": 2,
            "name": "Exit",
            "color": "#FFF3C8"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 4,
        "name": "East",
        "color": "#DBE4FF",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": null,
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 2,
        "zone_master_quality": [],
        "entry_exit": {
            "id": 2,
            "name": "Exit",
            "color": "#FFF3C8"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 3,
        "name": "East - West",
        "color": "#C8FFD7",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": null,
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 1,
        "zone_master_quality": [],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 2,
        "name": "West",
        "color": "#FFCEE2",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": null,
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 1,
        "zone_master_quality": [],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    },
    {
        "id": 1,
        "name": "East",
        "color": "#DBE4FF",
        "create_date": "2024-09-18T12:03:32.209Z",
        "update_date": null,
        "create_date_num": 1726635812,
        "update_date_num": null,
        "create_by": 1,
        "update_by": null,
        "description": "ok",
        "start_date": "2024-09-18T12:03:32.209Z",
        "end_date": null,
        "entry_exit_id": 1,
        "zone_master_quality": [
            {
                "id": 2,
                "name": null,
                "create_date": "2024-09-18T12:03:32.209Z",
                "update_date": "2024-09-18T13:43:28.978Z",
                "create_date_num": 1726635812,
                "update_date_num": 1726641808,
                "create_by": 1,
                "update_by": 1,
                "active": true,
                "c1_min": 10.99,
                "c1_max": null,
                "c3_min": null,
                "c3_max": null,
                "k5_min": null,
                "k5_max": null,
                "c7_min": null,
                "c7_max": null,
                "oxygen_min": null,
                "oxygen_max": null,
                "mercury_min": null,
                "mercury_max": null,
                "wobbe_index_min": null,
                "wobbe_index_max": null,
                "c2_min": null,
                "c2_max": null,
                "ic4_min": null,
                "ic4_max": null,
                "nc5_min": null,
                "nc5_max": null,
                "carbon_dioxide_min": null,
                "carbon_dioxide_max": null,
                "dew_point_min": null,
                "dew_point_max": null,
                "hydrogen_suifide_min": null,
                "hydrogen_suifide_max": null,
                "sg_min": null,
                "sg_max": null,
                "c2_plus_min": null,
                "c2_plus_max": null,
                "nc4_min": null,
                "nc4_max": null,
                "c6_min": null,
                "c6_max": null,
                "nitrogen_min": null,
                "nitrogen_max": null,
                "moisture_min": null,
                "moisture_max": null,
                "total_sulphur_min": null,
                "total_sulphur_max": null,
                "zone_master_id": null,
                "zone_id": 1
            }
        ],
        "entry_exit": {
            "id": 1,
            "name": "Entry",
            "color": "#C8FFD7"
        },
        "create_by_account": {
            "id": 1,
            "email": "admin@nueamek.fun",
            "first_name": "admin",
            "last_name": "nx"
        },
        "update_by_account": null
    }
]





export const data_table = {
    "name": "EAST-WEST",
    "description": "Entry EAST-WEST",
    "start_date": "2025-03-18T00:00:00.000Z",
}


// check data_table.start_date past present day