export const real_data_mock = {
    "sheet1": {
        "data": [
            [],
            [
                "SHIPPER ID",
                "CONTRACT CODE",
                "START DATE"
            ],
            [
                "SH03-2024-12",
                "vs001",
                "16/03/2025"
            ],
            [
                "Zone",
                "Supply/Demand",
                "Area",
                "POINT_ID",
                "W/HV",
                "Park/UnparkInstructed Flows",
                "Type",
                "Area_Code",
                "Subarea_Code",
                "Unit",
                "Entry_Exit",
                "WI",
                "HV",
                "SG",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "Total"
            ],
            [
                "WEST",
                "Supply",
                "Y",
                "N-entry-Y",
                "",
                "",
                "",
                "",
                "",
                "MMSCFD",
                "Entry",
                "7",
                "8",
                "9",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ],
            [
                "WEST",
                "Supply",
                "Y",
                "N-entry-Y",
                "",
                "",
                "",
                "",
                "",
                "MMBTU/D",
                "Entry",
                "6",
                "4",
                "3",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ],
            [
                "EAST",
                "Demand",
                "E",
                "N-exit-E",
                "",
                "",
                "",
                "",
                "",
                "MMBTU/D",
                "Exit",
                "4",
                "8",
                "8",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ],
            [
                "",
                "",
                "",
                "NPGC-01",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ],
            [
                "",
                "",
                "",
                "",
                "GQRC-01",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ],
            [
                "",
                "",
                "",
                "",
                "",
                "OC-01",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "480"
            ]
        ],
        "sheet": "Daily Nomination"
    },
    "sheet2": {
        "data": [
            [],
            [
                "Zone",
                "Point",
                "CO2",
                "C1",
                "C2",
                "C3",
                "iC4",
                "nC4",
                "iC5",
                "nC5",
                "C6",
                "C7",
                "C2+",
                "N2",
                "O2",
                "H2S",
                "S",
                "Hg"
            ],
            [
                "WEST",
                "N-entry-Y"
            ],
            [
                "EAST",
                "N-exit-E"
            ],
            [
                "*"
            ],
            [
                "ห้ามลบดอกจันด้านบน"
            ]
        ],
        "sheet": "Quality"
    },
    "sheet3": {
        "data": [
            [],
            [
                "Supply/Demand"
            ],
            [
                "Supply"
            ],
            [
                "Demand"
            ],
            [],
            [],
            [],
            [
                "WI/HV"
            ],
            [
                "East WI"
            ],
            [
                "East HV"
            ],
            [
                "East-West WI"
            ],
            [
                "East-West HV"
            ],
            [
                "West WI"
            ],
            [
                "West HV"
            ],
            [],
            [],
            [
                "Park/Unpark-Instructed Flows"
            ],
            [
                "Unpark"
            ],
            [
                "Instructed_Entry"
            ],
            [
                "Park"
            ],
            [
                "Instructed_Exit"
            ],
            [
                "Shrinkage_Volume"
            ],
            [
                "Min_Inventory_Change"
            ],
            [
                "Exchange_Mininventory"
            ],
            [],
            [],
            [
                "Type"
            ],
            [
                "Sales GSP"
            ],
            [
                "Bypass Gas"
            ],
            [
                "Common Header"
            ],
            [
                "Super Header"
            ],
            [
                "LNG"
            ],
            [
                "W-SUPPLY"
            ],
            [
                "Other"
            ],
            [
                "SPP"
            ],
            [
                "IND"
            ],
            [
                "NGV"
            ],
            [
                "NGD"
            ],
            [
                "FUEL"
            ],
            [
                "EGAT"
            ],
            [
                "IPP"
            ],
            [],
            [],
            [],
            [
                "Unit"
            ],
            [
                "MMBTU/D"
            ],
            [
                "MMSCFD"
            ],
            [
                "MMSCFH"
            ],
            [
                "%"
            ],
            [
                "BTU/SCF"
            ],
            [
                "Unitless"
            ],
            [
                "%.MOL"
            ],
            [
                "PPM.VOL"
            ],
            [
                "PPM.VOL.DEG"
            ],
            [
                "microG.M3"
            ],
            [
                "PPM.WEIGHT"
            ],
            [
                "LB.MMSCF"
            ],
            [
                "DEG.F"
            ],
            [
                "MJ/m3"
            ],
            [],
            [],
            [],
            [],
            [
                "Entry_Exit"
            ],
            [
                "Entry"
            ],
            [
                "Exit"
            ],
            [],
            [],
            [
                "Quality Parameters"
            ],
            [
                "CO2"
            ],
            [
                "C1"
            ],
            [
                "C2"
            ],
            [
                "C3"
            ],
            [
                "iC4"
            ],
            [
                "nC4"
            ],
            [
                "iC5"
            ],
            [
                "nC5"
            ],
            [
                "C6"
            ],
            [
                "C7"
            ],
            [
                "C2+"
            ],
            [
                "N2"
            ],
            [
                "O2"
            ],
            [
                "H2S"
            ],
            [
                "S"
            ],
            [
                "Hg"
            ],
            [
                "Total"
            ],
            [
                "LHV dry"
            ],
            [
                "LHV sat"
            ],
            [
                "HHV dry"
            ],
            [
                "HHV sat (Btu/scf)"
            ],
            [
                "SG"
            ],
            [
                "WI : HHVdry/sqrt(SG)"
            ],
            [
                "WI : MJ/m3"
            ]
        ],
        "sheet": "Lists"
    },
    "caseData": {
        "columnType": [],
        "columnParkUnparkinstructedFlows": [
            {
                "ix": 9,
                "row": [
                    "",
                    "",
                    "",
                    "",
                    "",
                    "OC-01",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            }
        ],
        "columnWHV": [
            {
                "ix": 8,
                "row": [
                    "",
                    "",
                    "",
                    "",
                    "GQRC-01",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            }
        ],
        "columnPointId": [
            {
                "ix": 4,
                "row": [
                    "WEST",
                    "Supply",
                    "Y",
                    "N-entry-Y",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "MMSCFD",
                    "Entry",
                    "7",
                    "8",
                    "9",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            },
            {
                "ix": 5,
                "row": [
                    "WEST",
                    "Supply",
                    "Y",
                    "N-entry-Y",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "MMBTU/D",
                    "Entry",
                    "6",
                    "4",
                    "3",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            },
            {
                "ix": 6,
                "row": [
                    "EAST",
                    "Demand",
                    "E",
                    "N-exit-E",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "MMBTU/D",
                    "Exit",
                    "4",
                    "8",
                    "8",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            }
        ],
        "columnPointIdConcept": [
            {
                "ix": 7,
                "row": [
                    "",
                    "",
                    "",
                    "NPGC-01",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "20",
                    "480"
                ]
            }
        ]
    },
    "informationData": {
        "columnType": [],
        "columnParkUnparkinstructedFlows": [],
        "columnWHV": [],
        "columnPointId": [],
        "columnPointIdConcept": []
    },
    "shipperInfo": {
        "shipper_id": 49,
        "contract_code_id": 101,
        "checkType": "Daily Nomination",
        "nomination_type_id": 1
    },
    "nominationFullJson": {
        "shiperInfo": {
            "0": {
                "SHIPPER ID": "SH03-2024-12"
            },
            "1": {
                "CONTRACT CODE": "vs001"
            },
            "2": {
                "START DATE": "16/03/2025"
            }
        },
        "headData": {
            "0": "Zone",
            "1": "Supply/Demand",
            "2": "Area",
            "3": "POINT_ID",
            "4": "W/HV",
            "5": "Park/UnparkInstructed Flows",
            "6": "Type",
            "7": "Area_Code",
            "8": "Subarea_Code",
            "9": "Unit",
            "10": "Entry_Exit",
            "11": "WI",
            "12": "HV",
            "13": "SG",
            "14": "1",
            "15": "2",
            "16": "3",
            "17": "4",
            "18": "5",
            "19": "6",
            "20": "7",
            "21": "8",
            "22": "9",
            "23": "10",
            "24": "11",
            "25": "12",
            "26": "13",
            "27": "14",
            "28": "15",
            "29": "16",
            "30": "17",
            "31": "18",
            "32": "19",
            "33": "20",
            "34": "21",
            "35": "22",
            "36": "23",
            "37": "24",
            "38": "Total"
        },
        "valueData": [
            {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMSCFD",
                "10": "Entry",
                "11": "7",
                "12": "8",
                "13": "9",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Entry",
                "11": "6",
                "12": "4",
                "13": "3",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "EAST",
                "1": "Demand",
                "2": "E",
                "3": "N-exit-E",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Exit",
                "11": "4",
                "12": "8",
                "13": "8",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "NPGC-01",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "GQRC-01",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "",
                "5": "OC-01",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            }
        ],
        "typeDoc": {
            "columnType": [],
            "columnParkUnparkinstructedFlows": [
                {
                    "ix": 9,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "",
                        "4": "",
                        "5": "OC-01",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnWHV": [
                {
                    "ix": 8,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "",
                        "4": "GQRC-01",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnPointId": [
                {
                    "ix": 4,
                    "row": {
                        "0": "WEST",
                        "1": "Supply",
                        "2": "Y",
                        "3": "N-entry-Y",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMSCFD",
                        "10": "Entry",
                        "11": "7",
                        "12": "8",
                        "13": "9",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                },
                {
                    "ix": 5,
                    "row": {
                        "0": "WEST",
                        "1": "Supply",
                        "2": "Y",
                        "3": "N-entry-Y",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMBTU/D",
                        "10": "Entry",
                        "11": "6",
                        "12": "4",
                        "13": "3",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                },
                {
                    "ix": 6,
                    "row": {
                        "0": "EAST",
                        "1": "Demand",
                        "2": "E",
                        "3": "N-exit-E",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMBTU/D",
                        "10": "Exit",
                        "11": "4",
                        "12": "8",
                        "13": "8",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnPointIdConcept": [
                {
                    "ix": 7,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "NPGC-01",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ]
        }
    },
    "renom": null,
    "sheet1Quality": [
        "For nomination point N-entry-Y, WI value (6) is out of zone limits (10 to 200)",
        "For nomination point N-entry-Y, HV value (4) is out of zone limits (10 to 100)",
        "For nomination point N-exit-E, WI value (4) is out of zone limits (0 to 0)",
        "For nomination point N-exit-E, HV value (8) is out of zone limits (0 to 0)"
    ],
    "sheet2Quality": [],
    "overuseQuantity": true,
    "overMaximumHourCapacityRight": true,
    "warningLogHr": [
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 1",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 2",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 3",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 4",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 5",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 6",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 7",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 8",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 9",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 10",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 11",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 12",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 13",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 14",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 15",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 16",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 17",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 18",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 19",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 20",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 21",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 22",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 23",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 24",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 1",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 2",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 3",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 4",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 5",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 6",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 7",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 8",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 9",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 10",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 11",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 12",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 13",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 14",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 15",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 16",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 17",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 18",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 19",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 20",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 21",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 22",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 23",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 24"
    ],
    "warningLogDay": [
        "Nominated energy 480 exceeds contracted value 0 for contract point N-entry-Y and gas day 16/03/2025",
        "Nominated energy 480 exceeds contracted value 0 for contract point N-exit-E and gas day 16/03/2025"
    ],
    "warningLogDayWeek": [],
    "exampleBookingFullJson": {
        "entryValue": [
            {
                "0": "Entry-Y",
                "5": "01/06/2025",
                "6": "01/09/2025",
                "7": "100",
                "8": "100",
                "9": "100",
                "10": "100",
                "11": "100",
                "12": "100",
                "13": "100",
                "14": "100",
                "15": "100",
                "16": "100",
                "17": "100",
                "18": "100"
            }
        ],
        "exitValue": [
            {
                "0": "Exit-E",
                "5": "01/06/2025",
                "6": "01/09/2025",
                "7": "100",
                "8": "100",
                "9": "100",
                "10": "100",
                "11": "100",
                "12": "100"
            }
        ],
        "headerEntry": {
            "Capacity Daily Booking (MMBTU/d)": {
                "01/06/2025": {
                    "key": "7"
                },
                "01/07/2025": {
                    "key": "8"
                },
                "01/08/2025": {
                    "key": "9"
                }
            },
            "Capacity Daily Booking (MMscfd)": {
                "01/06/2025": {
                    "key": "13"
                },
                "01/07/2025": {
                    "key": "14"
                },
                "01/08/2025": {
                    "key": "15"
                },
                "key": "13"
            },
            "Entry": {
                "Pressure Range": {
                    "Max": {
                        "key": "2"
                    },
                    "Min": {
                        "key": "1"
                    },
                    "key": "1"
                },
                "Temperature Range": {
                    "Max": {
                        "key": "4"
                    },
                    "Min": {
                        "key": "3"
                    },
                    "key": "3"
                },
                "key": "0"
            },
            "Maximum Hour Booking (MMBTU/h)": {
                "01/06/2025": {
                    "key": "10"
                },
                "01/07/2025": {
                    "key": "11"
                },
                "01/08/2025": {
                    "key": "12"
                },
                "key": "10"
            },
            "Maximum Hour Booking (MMscfh)": {
                "01/06/2025": {
                    "key": "16"
                },
                "01/07/2025": {
                    "key": "17"
                },
                "01/08/2025": {
                    "key": "18"
                },
                "key": "16"
            },
            "Period": {
                "From": {
                    "key": "5"
                },
                "To": {
                    "key": "6"
                },
                "key": "5"
            }
        },
        "headerExit": {
            "Capacity Daily Booking (MMBTU/d)": {
                "01/06/2025": {
                    "key": "7"
                },
                "01/07/2025": {
                    "key": "8"
                },
                "01/08/2025": {
                    "key": "9"
                }
            },
            "Exit": {
                "Pressure Range": {
                    "Max": {
                        "key": "2"
                    },
                    "Min": {
                        "key": "1"
                    },
                    "key": "1"
                },
                "Temperature Range": {
                    "Max": {
                        "key": "4"
                    },
                    "Min": {
                        "key": "3"
                    },
                    "key": "3"
                },
                "key": "0"
            },
            "Maximum Hour Booking (MMBTU/h)": {
                "01/06/2025": {
                    "key": "10"
                },
                "01/07/2025": {
                    "key": "11"
                },
                "01/08/2025": {
                    "key": "12"
                },
                "key": "10"
            },
            "Period": {
                "From": {
                    "key": "5"
                },
                "To": {
                    "key": "6"
                },
                "key": "5"
            }
        },
        "shipperInfo": {
            "0": {
                "Shipper Name": "GULF"
            },
            "1": {
                "Type of Contract": "SHORT_FIRM"
            },
            "2": {
                "Contract Code": "vs001"
            }
        },
        "sumEntries": {
            "0": "Sum Entry",
            "7": 100,
            "8": 100,
            "9": 100,
            "10": 100,
            "11": 100,
            "12": 100,
            "13": 100,
            "14": 100,
            "15": 100,
            "16": 100,
            "17": 100,
            "18": 100
        },
        "sumExits": {
            "0": "Sum Exit",
            "7": "100",
            "8": "100",
            "9": "100",
            "10": "100",
            "11": "100",
            "12": "100"
        }
    }
}

export const mod_data_mock = {
    "nominationFullJson": {
        "shiperInfo": {
            "0": {
                "SHIPPER ID": "SH03-2024-12"
            },
            "1": {
                "CONTRACT CODE": "vs001"
            },
            "2": {
                "START DATE": "16/03/2025"
            }
        },
        "headData": {
            "0": "Zone",
            "1": "Supply/Demand",
            "2": "Area",
            "3": "POINT_ID",
            "4": "W/HV",
            "5": "Park/UnparkInstructed Flows",
            "6": "Type",
            "7": "Area_Code",
            "8": "Subarea_Code",
            "9": "Unit",
            "10": "Entry_Exit",
            "11": "WI",
            "12": "HV",
            "13": "SG",
            "14": "1",
            "15": "2",
            "16": "3",
            "17": "4",
            "18": "5",
            "19": "6",
            "20": "7",
            "21": "8",
            "22": "9",
            "23": "10",
            "24": "11",
            "25": "12",
            "26": "13",
            "27": "14",
            "28": "15",
            "29": "16",
            "30": "17",
            "31": "18",
            "32": "19",
            "33": "20",
            "34": "21",
            "35": "22",
            "36": "23",
            "37": "24",
            "38": "Total"
        },
        "valueData": [
            {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMSCFD",
                "10": "Entry",
                "11": "7",
                "12": "8",
                "13": "9",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Entry",
                "11": "6",
                "12": "4",
                "13": "3",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "EAST",
                "1": "Demand",
                "2": "E",
                "3": "N-exit-E",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Exit",
                "11": "4",
                "12": "8",
                "13": "8",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "NPGC-01",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "GQRC-01",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "",
                "5": "OC-01",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            }
        ],
        "typeDoc": {
            "columnType": [],
            "columnParkUnparkinstructedFlows": [
                {
                    "ix": 9,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "",
                        "4": "",
                        "5": "OC-01",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnWHV": [
                {
                    "ix": 8,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "",
                        "4": "GQRC-01",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnPointId": [
                {
                    "ix": 4,
                    "row": {
                        "0": "WEST",
                        "1": "Supply",
                        "2": "Y",
                        "3": "N-entry-Y",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMSCFD",
                        "10": "Entry",
                        "11": "7",
                        "12": "8",
                        "13": "9",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                },
                {
                    "ix": 5,
                    "row": {
                        "0": "WEST",
                        "1": "Supply",
                        "2": "Y",
                        "3": "N-entry-Y",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMBTU/D",
                        "10": "Entry",
                        "11": "6",
                        "12": "4",
                        "13": "3",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                },
                {
                    "ix": 6,
                    "row": {
                        "0": "EAST",
                        "1": "Demand",
                        "2": "E",
                        "3": "N-exit-E",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "MMBTU/D",
                        "10": "Exit",
                        "11": "4",
                        "12": "8",
                        "13": "8",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ],
            "columnPointIdConcept": [
                {
                    "ix": 7,
                    "row": {
                        "0": "",
                        "1": "",
                        "2": "",
                        "3": "NPGC-01",
                        "4": "",
                        "5": "",
                        "6": "",
                        "7": "",
                        "8": "",
                        "9": "",
                        "10": "",
                        "11": "",
                        "12": "",
                        "13": "",
                        "14": "20",
                        "15": "20",
                        "16": "20",
                        "17": "20",
                        "18": "20",
                        "19": "20",
                        "20": "20",
                        "21": "20",
                        "22": "20",
                        "23": "20",
                        "24": "20",
                        "25": "20",
                        "26": "20",
                        "27": "20",
                        "28": "20",
                        "29": "20",
                        "30": "20",
                        "31": "20",
                        "32": "20",
                        "33": "20",
                        "34": "20",
                        "35": "20",
                        "36": "20",
                        "37": "20",
                        "38": "480"
                    }
                }
            ]
        }
    },
    "nominationRowJson": [
        {
            "zone_text": "WEST",
            "area_text": "Y",
            "entry_exit_id": 1,
            "data": {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMSCFD",
                "10": "Entry",
                "11": "7",
                "12": "8",
                "13": "9",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 4,
            "type": 1
        },
        {
            "zone_text": "WEST",
            "area_text": "Y",
            "entry_exit_id": 1,
            "data": {
                "0": "WEST",
                "1": "Supply",
                "2": "Y",
                "3": "N-entry-Y",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Entry",
                "11": "6",
                "12": "4",
                "13": "3",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 5,
            "type": 1
        },
        {
            "zone_text": "EAST",
            "area_text": "E",
            "entry_exit_id": 2,
            "data": {
                "0": "EAST",
                "1": "Demand",
                "2": "E",
                "3": "N-exit-E",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "MMBTU/D",
                "10": "Exit",
                "11": "4",
                "12": "8",
                "13": "8",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 6,
            "type": 1
        },
        {
            "zone_text": null,
            "area_text": null,
            "entry_exit_id": null,
            "data": {
                "0": "",
                "1": "",
                "2": "",
                "3": "NPGC-01",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 7,
            "type": 2
        },
        {
            "zone_text": null,
            "area_text": null,
            "entry_exit_id": null,
            "data": {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "",
                "5": "OC-01",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 9,
            "type": 4
        },
        {
            "zone_text": null,
            "area_text": null,
            "entry_exit_id": null,
            "data": {
                "0": "",
                "1": "",
                "2": "",
                "3": "",
                "4": "GQRC-01",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "20",
                "15": "20",
                "16": "20",
                "17": "20",
                "18": "20",
                "19": "20",
                "20": "20",
                "21": "20",
                "22": "20",
                "23": "20",
                "24": "20",
                "25": "20",
                "26": "20",
                "27": "20",
                "28": "20",
                "29": "20",
                "30": "20",
                "31": "20",
                "32": "20",
                "33": "20",
                "34": "20",
                "35": "20",
                "36": "20",
                "37": "20",
                "38": "480"
            },
            "old_index": 8,
            "type": 5
        }
    ],
    "nominationFullJsonSheet2": {
        "headData": {
            "0": "Zone",
            "1": "Point",
            "2": "CO2",
            "3": "C1",
            "4": "C2",
            "5": "C3",
            "6": "iC4",
            "7": "nC4",
            "8": "iC5",
            "9": "nC5",
            "10": "C6",
            "11": "C7",
            "12": "C2+",
            "13": "N2",
            "14": "O2",
            "15": "H2S",
            "16": "S",
            "17": "Hg"
        },
        "valueData": [
            {
                "0": "WEST",
                "1": "N-entry-Y",
                "2": "30",
                "3": "40",
                "4": "50",
                "5": "32",
                "6": "100",
                "7": "100",
                "8": "30",
                "9": "42",
                "10": "23",
                "11": "89",
                "12": "28",
                "13": "199",
                "14": "232",
                "15": "1999",
                "16": "2999",
                "17": "23"
            },
            {
                "0": "EAST",
                "1": "N-exit-E",
                "2": "67",
                "3": "92",
                "4": "987",
                "5": "234",
                "6": "200",
                "7": "300",
                "8": "499",
                "9": "199",
                "10": "178",
                "11": "356",
                "12": "20",
                "13": "776",
                "14": "200",
                "15": "300",
                "16": "410",
                "17": "20"
            }
        ]
    },
    "renom": null,
    "sheet1Quality": [
        "For nomination point N-entry-Y, WI value (6) is out of zone limits (10 to 200)",
        "For nomination point N-entry-Y, HV value (4) is out of zone limits (10 to 100)",
        "For nomination point N-exit-E, WI value (4) is out of zone limits (0 to 0)",
        "For nomination point N-exit-E, HV value (8) is out of zone limits (0 to 0)"
    ],
    "sheet2Quality": [
        "For nomination point S_GSP6RGC, WI value (1999) is out of zone limits (40 to 400)",
        "For nomination point S_GSP6RGC, WI value (23) is out of zone limits (40 to 7000)",
        "For nomination point S_GSP6RGC, WI value (67) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (92) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (20) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (776) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (200) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (300) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (410) is out of zone limits (0 to 0)",
        "For nomination point S_GSP6RGC, WI value (20) is out of zone limits (0 to 0)"
    ],
    "overuseQuantity": true,
    "overMaximumHourCapacityRight": true,
    "warningLogHr": [
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 1",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 2",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 3",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 4",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 5",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 6",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 7",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 8",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 9",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 10",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 11",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 12",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 13",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 14",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 15",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 16",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 17",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 18",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 19",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 20",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 21",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 22",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 23",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-entry-Y and hour 24",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 1",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 2",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 3",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 4",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 5",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 6",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 7",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 8",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 9",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 10",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 11",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 12",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 13",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 14",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 15",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 16",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 17",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 18",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 19",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 20",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 21",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 22",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 23",
        "Nominated max energy 20 exceeds contracted value 0 for contract point N-exit-E and hour 24"
    ],
    "warningLogDay": [
        "Nominated energy 480 exceeds contracted value 0 for contract point N-entry-Y and gas day 16/03/2025",
        "Nominated energy 480 exceeds contracted value 0 for contract point N-exit-E and gas day 16/03/2025"
    ],
    "warningLogDayWeek": [],
    "informationData": {
        "columnType": [],
        "columnParkUnparkinstructedFlows": [],
        "columnWHV": [],
        "columnPointId": [],
        "columnPointIdConcept": []
    }
}

// get group and contract_code from mock_data into new array and if group duplicate then remove it but if contract_code in duplicate group are not duplicate the move it 
export const mock_data = [
    {
        "id": 4,
        "nomination_code": "20250319-DNM-0003",
        "contract_code": {
            "id": 97,
            "contract_code": "2025-CSF-004",
            "submitted_timestamp": "2025-03-18T15:39:39.092Z",
            "contract_start_date": "2025-03-19T00:00:00.000Z",
            "contract_end_date": "2025-04-18T00:00:00.000Z",
        },
        "group": {
            "id": 30,
            "id_name": "SH_241204",
            "name": "EGAT",
            "company_name": "การไฟฟ้าฝ่ายผลิตแห่งประเทศไทย",
            "user_type_id": 3,
            "telephone": null,
            "email": "saraban-egat@egat.co.th",
            "address": "เลขที่ 53 หมู่ 2 ถนนจรัญสนิทวงศ์ ตำบลบางกรวย อำเภอบางกรวย จังหวัดนนทบุรี 11130",
            "bank_no": null,
            "start_date": "2024-12-04T00:00:00.000Z",
            "end_date": "2030-12-06T00:00:00.000Z",
            "status": true,
            "active": true,
            "create_date": "2024-12-04T10:16:11.595Z",
            "update_date": "2024-12-09T09:54:09.603Z",
            "bank_master_id": null,
            "create_by": 99999,
            "update_by": 99999,
            "time_num": null,
            "create_date_num": 1733282171,
            "update_date_num": 1733712849
        },
    },
    {
        "id": 3,
        "nomination_code": "20250319-DNM-0002",
        "contract_code": {
            "id": 98,
            "contract_code": "2025-CST-0005",
            "submitted_timestamp": "2025-03-19T14:32:23.298Z",
            "contract_start_date": "2025-04-01T00:00:00.000Z",
            "contract_end_date": "2025-07-01T00:00:00.000Z",
        },
        "group": {
            "id": 49,
            "id_name": "SH03-2024-12",
            "name": "GULF",
            "company_name": "Gulf Energy Development Public Company Limited",
            "user_type_id": 3,
            "telephone": "1234567890",
            "email": null,
            "address": "1/11 พานทอง ชลบุรี 20000",
            "bank_no": "888888888",
            "start_date": "2025-01-13T00:00:00.000Z",
            "end_date": "2025-08-31T00:00:00.000Z",
            "status": true,
            "active": true,
            "create_date": "2024-12-13T15:29:37.369Z",
            "update_date": "2025-02-06T15:43:06.221Z",
            "bank_master_id": 1,
            "create_by": 99998,
            "update_by": 42,
            "time_num": null,
            "create_date_num": 1734078577,
            "update_date_num": 1738831386
        },
    },
    {
        "id": 2,
        "nomination_code": "20250319-WNM-0001",
        "contract_code": {
            "id": 97,
            "contract_code": "2025-CSF-004",
            "submitted_timestamp": "2025-03-18T15:39:39.092Z",
            "contract_start_date": "2025-03-19T00:00:00.000Z",
            "contract_end_date": "2025-04-18T00:00:00.000Z",
        },
        "group": {
            "id": 30,
            "id_name": "SH_241204",
            "name": "EGAT",
            "company_name": "การไฟฟ้าฝ่ายผลิตแห่งประเทศไทย",
            "user_type_id": 3,
            "telephone": null,
            "email": "saraban-egat@egat.co.th",
            "address": "เลขที่ 53 หมู่ 2 ถนนจรัญสนิทวงศ์ ตำบลบางกรวย อำเภอบางกรวย จังหวัดนนทบุรี 11130",
            "bank_no": null,
            "start_date": "2024-12-04T00:00:00.000Z",
            "end_date": "2030-12-06T00:00:00.000Z",
            "status": true,
            "active": true,
            "create_date": "2024-12-04T10:16:11.595Z",
            "update_date": "2024-12-09T09:54:09.603Z",
            "bank_master_id": null,
            "create_by": 99999,
            "update_by": 99999,
            "time_num": null,
            "create_date_num": 1733282171,
            "update_date_num": 1733712849
        },
    },
    {
        "id": 1,
        "nomination_code": "20250319-DNM-0001",
        "contract_code": {
            "id": 95,
            "contract_code": "2025-CSF-002",
            "submitted_timestamp": "2025-03-18T14:05:26.302Z",
            "contract_start_date": "2025-03-19T00:00:00.000Z",
            "contract_end_date": "2025-04-18T00:00:00.000Z",
        },
        "group": {
            "id": 33,
            "id_name": "SH_241205-1",
            "name": "B.GRIMM",
            "company_name": "บริษัท บี.กริม เพาเวอร์ จำกัด (มหาชน)",
            "user_type_id": 3,
            "telephone": "025778888",
            "email": null,
            "address": "อาคาร ดร. เกฮาร์ด ลิงค์ 5 ถนนกรุงเทพกรีฑา แขวงหัวหมาก เขตบางกะปิ กรุงเทพฯ 10240 ประเทศไทย",
            "bank_no": null,
            "start_date": "2024-12-05T00:00:00.000Z",
            "end_date": "2030-12-08T00:00:00.000Z",
            "status": true,
            "active": true,
            "create_date": "2024-12-05T22:52:29.165Z",
            "update_date": "2024-12-08T22:22:44.615Z",
            "bank_master_id": null,
            "create_by": 99999,
            "update_by": 99999,
            "time_num": null,
            "create_date_num": 1733413949,
            "update_date_num": 1733671364
        },
    }
]