let body = {
    "contract_code_id": 119,
    "group_id": 6,
    "url": null,
    "data": [
        {
            "booking_row_json_id": 172,
            "temp_contract_point": "ENTRY_A",
            "temp_zone": "EAST",
            "temp_area": "A1",
            "temp_start_date": "01/02/2025",
            "temp_end_date": "30/04/2025",
            "total_contracted_mmbtu_d": 150,
            "total_release_mmbtu_d": 2,
            "entry_exit_id": 1,
            "pathMatch": {
                "id": 172,
                "entry": {
                    "name": "A1"
                },
                "exit": {
                    "name": "BB"
                }
            },
            "path": {
                "id": 184,
                "path_management_id": 40,
                "config_master_path_id": 15,
                "temps": {
                    "id": 15,
                    "path_no": "0001",
                    "create_date": "2024-09-24T14:13:47.961Z",
                    "update_date": "2024-10-06T00:07:50.277Z",
                    "create_date_num": 1727162027,
                    "update_date_num": 1728148070,
                    "create_by": 1,
                    "update_by": 1,
                    "active": true,
                    "revised_capacity_path": [
                        {
                            "id": 229,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 17,
                            "revised_capacity_path_type_id": 3,
                            "area": {
                                "id": 17,
                                "name": "FF",
                                "create_date": "2024-09-27T21:36:21.207Z",
                                "update_date": "2024-10-05T23:50:38.914Z",
                                "create_date_num": 1727447781,
                                "update_date_num": 1728147038,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-17T00:00:00.000Z",
                                "end_date": null,
                                "description": "FF",
                                "area_nominal_capacity": 213123,
                                "zone_id": 23,
                                "entry_exit_id": 2,
                                "color": "#ffccfb",
                                "supply_reference_quality_area": 12
                            }
                        },
                        {
                            "id": 227,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 16,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 16,
                                "name": "NE1",
                                "create_date": "2024-09-26T11:07:17.112Z",
                                "update_date": "2024-09-26T23:19:42.248Z",
                                "create_date_num": 1727323637,
                                "update_date_num": 1727367582,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": "2024-09-26T00:00:00.000Z",
                                "description": "test xxx",
                                "area_nominal_capacity": 100,
                                "zone_id": 22,
                                "entry_exit_id": 2,
                                "color": "#4fd6e8",
                                "supply_reference_quality_area": 10
                            }
                        },
                        {
                            "id": 228,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 11,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 11,
                                "name": "A4",
                                "create_date": "2024-09-25T15:39:52.590Z",
                                "update_date": "2024-09-30T13:44:38.236Z",
                                "create_date_num": 1727253592,
                                "update_date_num": 1727678678,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": null,
                                "description": "kkkkkk",
                                "area_nominal_capacity": 10000000,
                                "zone_id": 23,
                                "entry_exit_id": 2,
                                "color": "#FF0000",
                                "supply_reference_quality_area": 2
                            }
                        },
                        {
                            "id": 226,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 8,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 8,
                                "name": "XY",
                                "create_date": "2024-09-24T10:56:07.801Z",
                                "update_date": "2024-09-30T11:30:01.138Z",
                                "create_date_num": 1727150167,
                                "update_date_num": 1727670601,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": null,
                                "description": "XY",
                                "area_nominal_capacity": 100,
                                "zone_id": 21,
                                "entry_exit_id": 2,
                                "color": "#ff00ea",
                                "supply_reference_quality_area": 10
                            }
                        },
                        {
                            "id": 225,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 6,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 6,
                                "name": "BS",
                                "create_date": "2024-09-24T10:55:57.347Z",
                                "update_date": "2024-09-30T11:29:45.885Z",
                                "create_date_num": 1727150157,
                                "update_date_num": 1727670585,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": null,
                                "description": "BS",
                                "area_nominal_capacity": 100,
                                "zone_id": 22,
                                "entry_exit_id": 2,
                                "color": "#11ff00",
                                "supply_reference_quality_area": 10
                            }
                        },
                        {
                            "id": 224,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 5,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 5,
                                "name": "BB",
                                "create_date": "2024-09-24T10:55:47.849Z",
                                "update_date": "2024-12-11T14:08:40.941Z",
                                "create_date_num": 1727150147,
                                "update_date_num": 1733900920,
                                "create_by": 1,
                                "update_by": 25,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": "2025-12-27T00:00:00.000Z",
                                "description": "BB",
                                "area_nominal_capacity": 100,
                                "zone_id": 23,
                                "entry_exit_id": 2,
                                "color": "#6be6a0",
                                "supply_reference_quality_area": 10
                            }
                        },
                        {
                            "id": 223,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 3,
                            "revised_capacity_path_type_id": 2,
                            "area": {
                                "id": 3,
                                "name": "A2",
                                "create_date": "2024-09-18T14:19:44.011Z",
                                "update_date": "2024-12-26T02:01:41.806Z",
                                "create_date_num": 1726643984,
                                "update_date_num": 1735153301,
                                "create_by": 1,
                                "update_by": 1,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": "2024-12-10T00:00:00.000Z",
                                "description": "A2",
                                "area_nominal_capacity": 100,
                                "zone_id": 22,
                                "entry_exit_id": 2,
                                "color": "#80ddf4",
                                "supply_reference_quality_area": 10
                            }
                        },
                        {
                            "id": 222,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "area_id": 2,
                            "revised_capacity_path_type_id": 1,
                            "area": {
                                "id": 2,
                                "name": "A1",
                                "create_date": "2024-09-18T13:59:18.284Z",
                                "update_date": "2024-12-11T14:08:58.841Z",
                                "create_date_num": 1726642758,
                                "update_date_num": 1733900938,
                                "create_by": 1,
                                "update_by": 25,
                                "active": true,
                                "start_date": "2024-09-10T00:00:00.000Z",
                                "end_date": "2025-12-27T00:00:00.000Z",
                                "description": "A1",
                                "area_nominal_capacity": 100,
                                "zone_id": 13,
                                "entry_exit_id": 1,
                                "color": "#cb88dd",
                                "supply_reference_quality_area": null
                            }
                        }
                    ],
                    "revised_capacity_path_edges": [
                        {
                            "id": 152,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 2,
                            "target_id": 3
                        },
                        {
                            "id": 153,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 5,
                            "target_id": 6
                        },
                        {
                            "id": 154,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 8,
                            "target_id": 16
                        },
                        {
                            "id": 155,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 16,
                            "target_id": 11
                        },
                        {
                            "id": 156,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 11,
                            "target_id": 17
                        },
                        {
                            "id": 157,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 6,
                            "target_id": 8
                        },
                        {
                            "id": 158,
                            "create_date": "2024-10-06T00:07:50.309Z",
                            "update_date": null,
                            "create_date_num": 1728148070,
                            "update_date_num": null,
                            "create_by": 1,
                            "update_by": null,
                            "active": true,
                            "config_master_path_id": 15,
                            "source_id": 3,
                            "target_id": 5
                        }
                    ]
                },
                "temps_json": null,
                "start_date": "2025-01-15T00:00:00.000Z",
                "create_date": "2025-01-15T21:44:37.919Z",
                "update_date": null,
                "create_date_num": 1736952277,
                "update_date_num": null,
                "create_by": 26,
                "update_by": null,
                "flag_use": true,
                "exit_name_temp": "BB",
                "exit_id_temp": 5,
                "entryId": 2,
                "entryName": "A1",
                "findExit": [
                    {
                        "id": 229,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 17,
                        "revised_capacity_path_type_id": 3,
                        "area": {
                            "id": 17,
                            "name": "FF",
                            "create_date": "2024-09-27T21:36:21.207Z",
                            "update_date": "2024-10-05T23:50:38.914Z",
                            "create_date_num": 1727447781,
                            "update_date_num": 1728147038,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-17T00:00:00.000Z",
                            "end_date": null,
                            "description": "FF",
                            "area_nominal_capacity": 213123,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#ffccfb",
                            "supply_reference_quality_area": 12
                        }
                    },
                    {
                        "id": 227,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 16,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 16,
                            "name": "NE1",
                            "create_date": "2024-09-26T11:07:17.112Z",
                            "update_date": "2024-09-26T23:19:42.248Z",
                            "create_date_num": 1727323637,
                            "update_date_num": 1727367582,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2024-09-26T00:00:00.000Z",
                            "description": "test xxx",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#4fd6e8",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 228,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 11,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 11,
                            "name": "A4",
                            "create_date": "2024-09-25T15:39:52.590Z",
                            "update_date": "2024-09-30T13:44:38.236Z",
                            "create_date_num": 1727253592,
                            "update_date_num": 1727678678,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "kkkkkk",
                            "area_nominal_capacity": 10000000,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#FF0000",
                            "supply_reference_quality_area": 2
                        }
                    },
                    {
                        "id": 226,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 8,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 8,
                            "name": "XY",
                            "create_date": "2024-09-24T10:56:07.801Z",
                            "update_date": "2024-09-30T11:30:01.138Z",
                            "create_date_num": 1727150167,
                            "update_date_num": 1727670601,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "XY",
                            "area_nominal_capacity": 100,
                            "zone_id": 21,
                            "entry_exit_id": 2,
                            "color": "#ff00ea",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 225,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 6,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 6,
                            "name": "BS",
                            "create_date": "2024-09-24T10:55:57.347Z",
                            "update_date": "2024-09-30T11:29:45.885Z",
                            "create_date_num": 1727150157,
                            "update_date_num": 1727670585,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "BS",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#11ff00",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 224,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 5,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 5,
                            "name": "BB",
                            "create_date": "2024-09-24T10:55:47.849Z",
                            "update_date": "2024-12-11T14:08:40.941Z",
                            "create_date_num": 1727150147,
                            "update_date_num": 1733900920,
                            "create_by": 1,
                            "update_by": 25,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2025-12-27T00:00:00.000Z",
                            "description": "BB",
                            "area_nominal_capacity": 100,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#6be6a0",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 223,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 3,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 3,
                            "name": "A2",
                            "create_date": "2024-09-18T14:19:44.011Z",
                            "update_date": "2024-12-26T02:01:41.806Z",
                            "create_date_num": 1726643984,
                            "update_date_num": 1735153301,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2024-12-10T00:00:00.000Z",
                            "description": "A2",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#80ddf4",
                            "supply_reference_quality_area": 10
                        }
                    }
                ],
                "full": [
                    {
                        "id": 229,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 17,
                        "revised_capacity_path_type_id": 3,
                        "area": {
                            "id": 17,
                            "name": "FF",
                            "create_date": "2024-09-27T21:36:21.207Z",
                            "update_date": "2024-10-05T23:50:38.914Z",
                            "create_date_num": 1727447781,
                            "update_date_num": 1728147038,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-17T00:00:00.000Z",
                            "end_date": null,
                            "description": "FF",
                            "area_nominal_capacity": 213123,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#ffccfb",
                            "supply_reference_quality_area": 12
                        }
                    },
                    {
                        "id": 227,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 16,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 16,
                            "name": "NE1",
                            "create_date": "2024-09-26T11:07:17.112Z",
                            "update_date": "2024-09-26T23:19:42.248Z",
                            "create_date_num": 1727323637,
                            "update_date_num": 1727367582,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2024-09-26T00:00:00.000Z",
                            "description": "test xxx",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#4fd6e8",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 228,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 11,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 11,
                            "name": "A4",
                            "create_date": "2024-09-25T15:39:52.590Z",
                            "update_date": "2024-09-30T13:44:38.236Z",
                            "create_date_num": 1727253592,
                            "update_date_num": 1727678678,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "kkkkkk",
                            "area_nominal_capacity": 10000000,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#FF0000",
                            "supply_reference_quality_area": 2
                        }
                    },
                    {
                        "id": 226,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 8,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 8,
                            "name": "XY",
                            "create_date": "2024-09-24T10:56:07.801Z",
                            "update_date": "2024-09-30T11:30:01.138Z",
                            "create_date_num": 1727150167,
                            "update_date_num": 1727670601,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "XY",
                            "area_nominal_capacity": 100,
                            "zone_id": 21,
                            "entry_exit_id": 2,
                            "color": "#ff00ea",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 225,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 6,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 6,
                            "name": "BS",
                            "create_date": "2024-09-24T10:55:57.347Z",
                            "update_date": "2024-09-30T11:29:45.885Z",
                            "create_date_num": 1727150157,
                            "update_date_num": 1727670585,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": null,
                            "description": "BS",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#11ff00",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 224,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 5,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 5,
                            "name": "BB",
                            "create_date": "2024-09-24T10:55:47.849Z",
                            "update_date": "2024-12-11T14:08:40.941Z",
                            "create_date_num": 1727150147,
                            "update_date_num": 1733900920,
                            "create_by": 1,
                            "update_by": 25,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2025-12-27T00:00:00.000Z",
                            "description": "BB",
                            "area_nominal_capacity": 100,
                            "zone_id": 23,
                            "entry_exit_id": 2,
                            "color": "#6be6a0",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 223,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 3,
                        "revised_capacity_path_type_id": 2,
                        "area": {
                            "id": 3,
                            "name": "A2",
                            "create_date": "2024-09-18T14:19:44.011Z",
                            "update_date": "2024-12-26T02:01:41.806Z",
                            "create_date_num": 1726643984,
                            "update_date_num": 1735153301,
                            "create_by": 1,
                            "update_by": 1,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2024-12-10T00:00:00.000Z",
                            "description": "A2",
                            "area_nominal_capacity": 100,
                            "zone_id": 22,
                            "entry_exit_id": 2,
                            "color": "#80ddf4",
                            "supply_reference_quality_area": 10
                        }
                    },
                    {
                        "id": 222,
                        "create_date": "2024-10-06T00:07:50.309Z",
                        "update_date": null,
                        "create_date_num": 1728148070,
                        "update_date_num": null,
                        "create_by": 1,
                        "update_by": null,
                        "active": true,
                        "config_master_path_id": 15,
                        "area_id": 2,
                        "revised_capacity_path_type_id": 1,
                        "area": {
                            "id": 2,
                            "name": "A1",
                            "create_date": "2024-09-18T13:59:18.284Z",
                            "update_date": "2024-12-11T14:08:58.841Z",
                            "create_date_num": 1726642758,
                            "update_date_num": 1733900938,
                            "create_by": 1,
                            "update_by": 25,
                            "active": true,
                            "start_date": "2024-09-10T00:00:00.000Z",
                            "end_date": "2025-12-27T00:00:00.000Z",
                            "description": "A1",
                            "area_nominal_capacity": 100,
                            "zone_id": 13,
                            "entry_exit_id": 1,
                            "color": "#cb88dd",
                            "supply_reference_quality_area": null
                        }
                    }
                ]
            }
        }
    ]
}